import type { WhoAmIWord } from "./types";

export const WHO_AM_I_WORDS_EN: WhoAmIWord[] = [
  // ANIMALS
  { id: "a1", word: "Dog", emoji: "🐶" },
  { id: "a2", word: "Cat", emoji: "🐱" },
  { id: "a3", word: "Horse", emoji: "🐴" },
  { id: "a4", word: "Cow", emoji: "🐮" },
  { id: "a5", word: "Pig", emoji: "🐷" },
  { id: "a6", word: "Sheep", emoji: "🐑" },
  { id: "a7", word: "Hen", emoji: "🐔" },
  { id: "a8", word: "Duck", emoji: "🦆" },
  { id: "a9", word: "Lion", emoji: "🦁" },
  { id: "a10", word: "Tiger", emoji: "🐯" },
  { id: "a11", word: "Elephant", emoji: "🐘" },
  { id: "a12", word: "Giraffe", emoji: "🦒" },
  { id: "a13", word: "Monkey", emoji: "🐵" },
  { id: "a14", word: "Bear", emoji: "🐻" },
  { id: "a15", word: "Snake", emoji: "🐍" },
  { id: "a16", word: "Bird", emoji: "🐦" },
  { id: "a17", word: "Fish", emoji: "🐟" },
  { id: "a18", word: "Shark", emoji: "🦈" },
  { id: "a19", word: "Whale", emoji: "🐳" },
  { id: "a20", word: "Dolphin", emoji: "🐬" },

  // FOOD & FRUIT
  { id: "c1", word: "Apple", emoji: "🍎" },
  { id: "c2", word: "Banana", emoji: "🍌" },
  { id: "c3", word: "Orange", emoji: "🍊" },
  { id: "c4", word: "Grape", emoji: "🍇" },
  { id: "c5", word: "Strawberry", emoji: "🍓" },
  { id: "c6", word: "Watermelon", emoji: "🍉" },
  { id: "c7", word: "Melon", emoji: "🍈" },
  { id: "c8", word: "Lemon", emoji: "🍋" },
  { id: "c9", word: "Tomato", emoji: "🍅" },
  { id: "c10", word: "Carrot", emoji: "🥕" },
  { id: "c11", word: "Potato", emoji: "🥔" },
  { id: "c12", word: "Onion", emoji: "🧅" },
  { id: "c13", word: "Lettuce", emoji: "🥬" },
  { id: "c14", word: "Hamburger", emoji: "🍔" },
  { id: "c15", word: "Pizza", emoji: "🍕" },
  { id: "c16", word: "Ice cream", emoji: "🍦" },
  { id: "c17", word: "Chocolate", emoji: "🍫" },
  { id: "c18", word: "Cookie", emoji: "🍪" },
  { id: "c19", word: "Cake", emoji: "🎂" },
  { id: "c20", word: "Candy", emoji: "🍬" },

  // HOUSEHOLD OBJECTS
  { id: "o1", word: "Bed", emoji: "🛏️" },
  { id: "o2", word: "Chair", emoji: "🪑" },
  { id: "o3", word: "Table", emoji: "🍽️" },
  { id: "o4", word: "Sofa", emoji: "🛋️" },
  { id: "o5", word: "Door", emoji: "🚪" },
  { id: "o6", word: "Window", emoji: "🪟" },
  { id: "o7", word: "Television", emoji: "📺" },
  { id: "o8", word: "Refrigerator", emoji: "🧊" },
  { id: "o9", word: "Microwave", emoji: "⏲️" },
  { id: "o10", word: "Washing machine", emoji: "🧺" },
  { id: "o11", word: "Plate", emoji: "🍽️" },
  { id: "o12", word: "Glass", emoji: "🥛" },
  { id: "o13", word: "Fork", emoji: "🍴" },
  { id: "o14", word: "Spoon", emoji: "🥄" },
  { id: "o15", word: "Knife", emoji: "🔪" },
  { id: "o16", word: "Towel", emoji: "🧻" },
  { id: "o17", word: "Soap", emoji: "🧼" },
  { id: "o18", word: "Toothbrush", emoji: "🪥" },
  { id: "o19", word: "Comb", emoji: "💇" },
  { id: "o20", word: "Mirror", emoji: "🪞" },

  // TOYS, VEHICLES & NATURE
  { id: "j1", word: "Ball", emoji: "⚽" },
  { id: "j2", word: "Doll", emoji: "🪆" },
  { id: "j3", word: "Toy car", emoji: "🚙" },
  { id: "j4", word: "Puzzle", emoji: "🧩" },
  { id: "j5", word: "Bicycle", emoji: "🚲" },
  { id: "j6", word: "Car", emoji: "🚗" },
  { id: "j7", word: "Airplane", emoji: "✈️" },
  { id: "j8", word: "Boat", emoji: "⛵" },
  { id: "j9", word: "Train", emoji: "🚆" },
  { id: "j10", word: "Bus", emoji: "🚌" },
  { id: "j11", word: "Sun", emoji: "☀️" },
  { id: "j12", word: "Moon", emoji: "🌙" },
  { id: "j13", word: "Star", emoji: "⭐" },
  { id: "j14", word: "Cloud", emoji: "☁️" },
  { id: "j15", word: "Rain", emoji: "🌧️" },
  { id: "j16", word: "Snow", emoji: "❄️" },
  { id: "j17", word: "Tree", emoji: "🌳" },
  { id: "j18", word: "Flower", emoji: "🌸" },
  { id: "j19", word: "Mountain", emoji: "⛰️" },
  { id: "j20", word: "River", emoji: "🏞️" },
  { id: "j21", word: "Beach", emoji: "🏖️" },
  { id: "j22", word: "Red", emoji: "🔴" },
  { id: "j23", word: "Blue", emoji: "🔵" },
  { id: "j24", word: "Green", emoji: "🟢" },
  { id: "j25", word: "Yellow", emoji: "🟡" },

  // ANIMALS 2
  { id: "a21", word: "Bee", emoji: "🐝" },
  { id: "a22", word: "Butterfly", emoji: "🦋" },
  { id: "a23", word: "Ant", emoji: "🐜" },
  { id: "a24", word: "Spider", emoji: "🕷️" },
  { id: "a25", word: "Frog", emoji: "🐸" },
  { id: "a26", word: "Turtle", emoji: "🐢" },
  { id: "a27", word: "Rabbit", emoji: "🐰" },
  { id: "a28", word: "Squirrel", emoji: "🐿️" },
  { id: "a29", word: "Fox", emoji: "🦊" },
  { id: "a30", word: "Wolf", emoji: "🐺" },
  { id: "a31", word: "Zebra", emoji: "🦓" },
  { id: "a32", word: "Kangaroo", emoji: "🦘" },
  { id: "a33", word: "Koala", emoji: "🐨" },
  { id: "a34", word: "Owl", emoji: "🦉" },
  { id: "a35", word: "Penguin", emoji: "🐧" },

  // FOOD 2
  { id: "c21", word: "Bread", emoji: "🍞" },
  { id: "c22", word: "Cheese", emoji: "🧀" },
  { id: "c23", word: "Egg", emoji: "🥚" },
  { id: "c24", word: "Milk", emoji: "🥛" },
  { id: "c25", word: "Juice", emoji: "🧃" },
  { id: "c26", word: "Soup", emoji: "🍲" },
  { id: "c27", word: "Salad", emoji: "🥗" },
  { id: "c28", word: "Rice", emoji: "🍚" },
  { id: "c29", word: "Noodles", emoji: "🍝" },
  { id: "c30", word: "Chicken", emoji: "🍗" },
  { id: "c31", word: "Seafood", emoji: "🐟" },
  { id: "c32", word: "Honey", emoji: "🍯" },
  { id: "c33", word: "Jam", emoji: "🫙" },
  { id: "c34", word: "Popcorn", emoji: "🍿" },
  { id: "c35", word: "Mate tea", emoji: "🧉" },

  // HOME 2
  { id: "o21", word: "Candle", emoji: "🕯️" },
  { id: "o22", word: "Padlock", emoji: "🔒" },
  { id: "o23", word: "Lamp", emoji: "💡" },
  { id: "o24", word: "Clock", emoji: "⏰" },
  { id: "o25", word: "Key", emoji: "🔑" },
  { id: "o26", word: "Broom", emoji: "🧹" },
  { id: "o27", word: "Bucket", emoji: "🪣" },
  { id: "o28", word: "Umbrella", emoji: "☂️" },
  { id: "o29", word: "Backpack", emoji: "🎒" },
  { id: "o30", word: "Calendar", emoji: "📅" },
  { id: "o31", word: "Radio", emoji: "📻" },
  { id: "o32", word: "Computer", emoji: "💻" },
  { id: "o33", word: "Phone", emoji: "📱" },
  { id: "o34", word: "Plug", emoji: "🔌" },

  // CLOTHES
  { id: "r1", word: "Shirt", emoji: "👕" },
  { id: "r2", word: "Pants", emoji: "👖" },
  { id: "r3", word: "Shoe", emoji: "👟" },
  { id: "r4", word: "Cap", emoji: "🧢" },
  { id: "r5", word: "Scarf", emoji: "🧣" },
  { id: "r6", word: "Gloves", emoji: "🧤" },
  { id: "r7", word: "Dress", emoji: "👗" },
  { id: "r8", word: "Socks", emoji: "🧦" },
  { id: "r9", word: "Jacket", emoji: "🧥" },
  { id: "r10", word: "Ring", emoji: "💍" },
  { id: "r11", word: "Hat", emoji: "🎩" },

  // SPORTS
  { id: "d1", word: "Basketball", emoji: "🏀" },
  { id: "d2", word: "Tennis", emoji: "🎾" },
  { id: "d3", word: "Swimming", emoji: "🏊" },
  { id: "d4", word: "Volleyball", emoji: "🏐" },
  { id: "d5", word: "Boxing", emoji: "🥊" },
  { id: "d6", word: "Karate", emoji: "🥋" },
  { id: "d7", word: "Cycling", emoji: "🚴" },
  { id: "d8", word: "Skating", emoji: "🛼" },
  { id: "d9", word: "Golf", emoji: "🏌️" },
  { id: "d10", word: "Surfing", emoji: "🏄" },

  // MUSIC
  { id: "m1", word: "Guitar", emoji: "🎸" },
  { id: "m2", word: "Piano", emoji: "🎹" },
  { id: "m3", word: "Drum", emoji: "🥁" },
  { id: "m4", word: "Violin", emoji: "🎻" },
  { id: "m5", word: "Flute", emoji: "🪈" },
  { id: "m6", word: "Trumpet", emoji: "🎺" },
  { id: "m7", word: "Microphone", emoji: "🎤" },
  { id: "m8", word: "Maracas", emoji: "🪇" },

  // NATURE 2
  { id: "n1", word: "Wind", emoji: "💨" },
  { id: "n2", word: "Thunder", emoji: "⛈️" },
  { id: "n3", word: "Lightning", emoji: "⚡" },
  { id: "n4", word: "Rainbow", emoji: "🌈" },
  { id: "n5", word: "Volcano", emoji: "🌋" },
  { id: "n6", word: "Desert", emoji: "🏜️" },
  { id: "n7", word: "Forest", emoji: "🌲" },
  { id: "n8", word: "Island", emoji: "🏝️" },
  { id: "n9", word: "Rock", emoji: "🪨" },
  { id: "n10", word: "Shooting star", emoji: "🌠" },

  // SCHOOL
  { id: "e1", word: "Pencil", emoji: "✏️" },
  { id: "e2", word: "Scissors", emoji: "✂️" },
  { id: "e3", word: "Notebook", emoji: "📓" },
  { id: "e4", word: "Book", emoji: "📖" },
  { id: "e5", word: "Blackboard", emoji: "📝" },
  { id: "e6", word: "Ruler", emoji: "📏" },
  { id: "e7", word: "Calculator", emoji: "🧮" },
  { id: "e8", word: "Pen", emoji: "🖊️" },

  // BODY
  { id: "b1", word: "Hand", emoji: "✋" },
  { id: "b2", word: "Foot", emoji: "🦶" },
  { id: "b3", word: "Eye", emoji: "👁️" },
  { id: "b4", word: "Nose", emoji: "👃" },
  { id: "b5", word: "Ear", emoji: "👂" },
  { id: "b6", word: "Mouth", emoji: "👄" },
  { id: "b7", word: "Tooth", emoji: "🦷" },
  { id: "b8", word: "Hair", emoji: "🦱" },
  { id: "b9", word: "Heart", emoji: "❤️" },
];
