import type { WhoAmIWord } from "./types";

export const WHO_AM_I_WORDS_EN: WhoAmIWord[] = [
  // ANIMALS
  { id: "a1", word: "Dog", emoji: "🐶" },
  { id: "a2", word: "Cat", emoji: "🐱" },
  { id: "a3", word: "Horse", emoji: "🐴" },
  { id: "a4", word: "Cow", emoji: "🐮" },
  { id: "a5", word: "Pig", emoji: "🐷" },
  { id: "a6", word: "Sheep", emoji: "🐑" },
  { id: "a7", word: "Hen", emoji: "🐔" },
  { id: "a8", word: "Duck", emoji: "🦆" },
  { id: "a9", word: "Lion", emoji: "🦁" },
  { id: "a10", word: "Tiger", emoji: "🐯" },
  { id: "a11", word: "Elephant", emoji: "🐘" },
  { id: "a12", word: "Giraffe", emoji: "🦒" },
  { id: "a13", word: "Monkey", emoji: "🐵" },
  { id: "a14", word: "Bear", emoji: "🐻" },
  { id: "a15", word: "Snake", emoji: "🐍" },
  { id: "a16", word: "Bird", emoji: "🐦" },
  { id: "a17", word: "Fish", emoji: "🐟" },
  { id: "a18", word: "Shark", emoji: "🦈" },
  { id: "a19", word: "Whale", emoji: "🐳" },
  { id: "a20", word: "Dolphin", emoji: "🐬" },

  // FOOD & FRUIT
  { id: "c1", word: "Apple", emoji: "🍎" },
  { id: "c2", word: "Banana", emoji: "🍌" },
  { id: "c3", word: "Orange", emoji: "🍊" },
  { id: "c4", word: "Grape", emoji: "🍇" },
  { id: "c5", word: "Strawberry", emoji: "🍓" },
  { id: "c6", word: "Watermelon", emoji: "🍉" },
  { id: "c7", word: "Melon", emoji: "🍈" },
  { id: "c8", word: "Lemon", emoji: "🍋" },
  { id: "c9", word: "Tomato", emoji: "🍅" },
  { id: "c10", word: "Carrot", emoji: "🥕" },
  { id: "c11", word: "Potato", emoji: "🥔" },
  { id: "c12", word: "Onion", emoji: "🧅" },
  { id: "c13", word: "Lettuce", emoji: "🥬" },
  { id: "c14", word: "Hamburger", emoji: "🍔" },
  { id: "c15", word: "Pizza", emoji: "🍕" },
  { id: "c16", word: "Ice cream", emoji: "🍦" },
  { id: "c17", word: "Chocolate", emoji: "🍫" },
  { id: "c18", word: "Cookie", emoji: "🍪" },
  { id: "c19", word: "Cake", emoji: "🎂" },
  { id: "c20", word: "Candy", emoji: "🍬" },

  // HOUSEHOLD OBJECTS
  { id: "o1", word: "Bed", emoji: "🛏️" },
  { id: "o2", word: "Chair", emoji: "🪑" },
  { id: "o3", word: "Table", emoji: "🍽️" },
  { id: "o4", word: "Sofa", emoji: "🛋️" },
  { id: "o5", word: "Door", emoji: "🚪" },
  { id: "o6", word: "Window", emoji: "🪟" },
  { id: "o7", word: "Television", emoji: "📺" },
  { id: "o8", word: "Refrigerator", emoji: "🧊" },
  { id: "o9", word: "Microwave", emoji: "⏲️" },
  { id: "o10", word: "Washing machine", emoji: "🧺" },
  { id: "o11", word: "Plate", emoji: "🍽️" },
  { id: "o12", word: "Glass", emoji: "🥛" },
  { id: "o13", word: "Fork", emoji: "🍴" },
  { id: "o14", word: "Spoon", emoji: "🥄" },
  { id: "o15", word: "Knife", emoji: "🔪" },
  { id: "o16", word: "Towel", emoji: "🧻" },
  { id: "o17", word: "Soap", emoji: "🧼" },
  { id: "o18", word: "Toothbrush", emoji: "🪥" },
  { id: "o19", word: "Comb", emoji: "💇" },
  { id: "o20", word: "Mirror", emoji: "🪞" },

  // TOYS, VEHICLES & NATURE
  { id: "j1", word: "Ball", emoji: "⚽" },
  { id: "j2", word: "Doll", emoji: "🪆" },
  { id: "j3", word: "Toy car", emoji: "🚙" },
  { id: "j4", word: "Puzzle", emoji: "🧩" },
  { id: "j5", word: "Bicycle", emoji: "🚲" },
  { id: "j6", word: "Car", emoji: "🚗" },
  { id: "j7", word: "Airplane", emoji: "✈️" },
  { id: "j8", word: "Boat", emoji: "⛵" },
  { id: "j9", word: "Train", emoji: "🚆" },
  { id: "j10", word: "Bus", emoji: "🚌" },
  { id: "j11", word: "Sun", emoji: "☀️" },
  { id: "j12", word: "Moon", emoji: "🌙" },
  { id: "j13", word: "Star", emoji: "⭐" },
  { id: "j14", word: "Cloud", emoji: "☁️" },
  { id: "j15", word: "Rain", emoji: "🌧️" },
  { id: "j16", word: "Snow", emoji: "❄️" },
  { id: "j17", word: "Tree", emoji: "🌳" },
  { id: "j18", word: "Flower", emoji: "🌸" },
  { id: "j19", word: "Mountain", emoji: "⛰️" },
  { id: "j20", word: "River", emoji: "🏞️" },
  { id: "j21", word: "Beach", emoji: "🏖️" },
  { id: "j22", word: "Red", emoji: "🔴" },
  { id: "j23", word: "Blue", emoji: "🔵" },
  { id: "j24", word: "Green", emoji: "🟢" },
  { id: "j25", word: "Yellow", emoji: "🟡" },
];
