import type { WhoAmIWord } from "./types";

export const WHO_AM_I_WORDS_ES: WhoAmIWord[] = [
  // ANIMALES
  { id: "a1", word: "Perro", emoji: "🐶" },
  { id: "a2", word: "Gato", emoji: "🐱" },
  { id: "a3", word: "Caballo", emoji: "🐴" },
  { id: "a4", word: "Vaca", emoji: "🐮" },
  { id: "a5", word: "Cerdo", emoji: "🐷" },
  { id: "a6", word: "Oveja", emoji: "🐑" },
  { id: "a7", word: "Gallina", emoji: "🐔" },
  { id: "a8", word: "Pato", emoji: "🦆" },
  { id: "a9", word: "León", emoji: "🦁" },
  { id: "a10", word: "Tigre", emoji: "🐯" },
  { id: "a11", word: "Elefante", emoji: "🐘" },
  { id: "a12", word: "Jirafa", emoji: "🦒" },
  { id: "a13", word: "Mono", emoji: "🐵" },
  { id: "a14", word: "Oso", emoji: "🐻" },
  { id: "a15", word: "Serpiente", emoji: "🐍" },
  { id: "a16", word: "Pájaro", emoji: "🐦" },
  { id: "a17", word: "Pez", emoji: "🐟" },
  { id: "a18", word: "Tiburón", emoji: "🦈" },
  { id: "a19", word: "Ballena", emoji: "🐳" },
  { id: "a20", word: "Delfín", emoji: "🐬" },

  // COMIDAS Y FRUTAS
  { id: "c1", word: "Manzana", emoji: "🍎" },
  { id: "c2", word: "Banana", emoji: "🍌" },
  { id: "c3", word: "Naranja", emoji: "🍊" },
  { id: "c4", word: "Uva", emoji: "🍇" },
  { id: "c5", word: "Fresa", emoji: "🍓" },
  { id: "c6", word: "Sandía", emoji: "🍉" },
  { id: "c7", word: "Melón", emoji: "🍈" },
  { id: "c8", word: "Limón", emoji: "🍋" },
  { id: "c9", word: "Tomate", emoji: "🍅" },
  { id: "c10", word: "Zanahoria", emoji: "🥕" },
  { id: "c11", word: "Papa", emoji: "🥔" },
  { id: "c12", word: "Cebolla", emoji: "🧅" },
  { id: "c13", word: "Lechuga", emoji: "🥬" },
  { id: "c14", word: "Hamburguesa", emoji: "🍔" },
  { id: "c15", word: "Pizza", emoji: "🍕" },
  { id: "c16", word: "Helado", emoji: "🍦" },
  { id: "c17", word: "Chocolate", emoji: "🍫" },
  { id: "c18", word: "Galleta", emoji: "🍪" },
  { id: "c19", word: "Pastel", emoji: "🎂" },
  { id: "c20", word: "Caramelo", emoji: "🍬" },

  // OBJETOS DE LA CASA
  { id: "o1", word: "Cama", emoji: "🛏️" },
  { id: "o2", word: "Silla", emoji: "🪑" },
  { id: "o3", word: "Mesa", emoji: "🍽️" },
  { id: "o4", word: "Sofá", emoji: "🛋️" },
  { id: "o5", word: "Puerta", emoji: "🚪" },
  { id: "o6", word: "Ventana", emoji: "🪟" },
  { id: "o7", word: "Televisión", emoji: "📺" },
  { id: "o8", word: "Refrigerador", emoji: "🧊" },
  { id: "o9", word: "Microondas", emoji: "⏲️" },
  { id: "o10", word: "Lavadora", emoji: "🧺" },
  { id: "o11", word: "Plato", emoji: "🍽️" },
  { id: "o12", word: "Vaso", emoji: "🥛" },
  { id: "o13", word: "Tenedor", emoji: "🍴" },
  { id: "o14", word: "Cuchara", emoji: "🥄" },
  { id: "o15", word: "Cuchillo", emoji: "🔪" },
  { id: "o16", word: "Toalla", emoji: "🧻" },
  { id: "o17", word: "Jabón", emoji: "🧼" },
  { id: "o18", word: "Cepillo de dientes", emoji: "🪥" },
  { id: "o19", word: "Peine", emoji: "💇" },
  { id: "o20", word: "Espejo", emoji: "🪞" },

  // JUGUETES, VEHICULOS Y NATURALEZA
  { id: "j1", word: "Pelota", emoji: "⚽" },
  { id: "j2", word: "Muñeca", emoji: "🪆" },
  { id: "j3", word: "Coche de juguete", emoji: "🚙" },
  { id: "j4", word: "Rompecabezas", emoji: "🧩" },
  { id: "j5", word: "Bicicleta", emoji: "🚲" },
  { id: "j6", word: "Coche", emoji: "🚗" },
  { id: "j7", word: "Avión", emoji: "✈️" },
  { id: "j8", word: "Barco", emoji: "⛵" },
  { id: "j9", word: "Tren", emoji: "🚆" },
  { id: "j10", word: "Autobús", emoji: "🚌" },
  { id: "j11", word: "Sol", emoji: "☀️" },
  { id: "j12", word: "Luna", emoji: "🌙" },
  { id: "j13", word: "Estrella", emoji: "⭐" },
  { id: "j14", word: "Nube", emoji: "☁️" },
  { id: "j15", word: "Lluvia", emoji: "🌧️" },
  { id: "j16", word: "Nieve", emoji: "❄️" },
  { id: "j17", word: "Árbol", emoji: "🌳" },
  { id: "j18", word: "Flor", emoji: "🌸" },
  { id: "j19", word: "Montaña", emoji: "⛰️" },
  { id: "j20", word: "Río", emoji: "🏞️" },
  { id: "j21", word: "Playa", emoji: "🏖️" },
  { id: "j22", word: "Rojo", emoji: "🔴" },
  { id: "j23", word: "Azul", emoji: "🔵" },
  { id: "j24", word: "Verde", emoji: "🟢" },
  { id: "j25", word: "Amarillo", emoji: "🟡" },

  // ANIMALES 2
  { id: "a21", word: "Abeja", emoji: "🐝" },
  { id: "a22", word: "Mariposa", emoji: "🦋" },
  { id: "a23", word: "Hormiga", emoji: "🐜" },
  { id: "a24", word: "Araña", emoji: "🕷️" },
  { id: "a25", word: "Rana", emoji: "🐸" },
  { id: "a26", word: "Tortuga", emoji: "🐢" },
  { id: "a27", word: "Conejo", emoji: "🐰" },
  { id: "a28", word: "Ardilla", emoji: "🐿️" },
  { id: "a29", word: "Zorro", emoji: "🦊" },
  { id: "a30", word: "Lobo", emoji: "🐺" },
  { id: "a31", word: "Cebra", emoji: "🦓" },
  { id: "a32", word: "Canguro", emoji: "🦘" },
  { id: "a33", word: "Koala", emoji: "🐨" },
  { id: "a34", word: "Búho", emoji: "🦉" },
  { id: "a35", word: "Pingüino", emoji: "🐧" },

  // COMIDA 2
  { id: "c21", word: "Pan", emoji: "🍞" },
  { id: "c22", word: "Queso", emoji: "🧀" },
  { id: "c23", word: "Huevo", emoji: "🥚" },
  { id: "c24", word: "Leche", emoji: "🥛" },
  { id: "c25", word: "Jugo", emoji: "🧃" },
  { id: "c26", word: "Sopa", emoji: "🍲" },
  { id: "c27", word: "Ensalada", emoji: "🥗" },
  { id: "c28", word: "Arroz", emoji: "🍚" },
  { id: "c29", word: "Fideos", emoji: "🍝" },
  { id: "c30", word: "Pollo", emoji: "🍗" },
  { id: "c31", word: "Pescado", emoji: "🐟" },
  { id: "c32", word: "Miel", emoji: "🍯" },
  { id: "c33", word: "Mermelada", emoji: "🫙" },
  { id: "c34", word: "Pochoclo", emoji: "🍿" },
  { id: "c35", word: "Mate", emoji: "🧉" },

  // CASA 2
  { id: "o21", word: "Vela", emoji: "🕯️" },
  { id: "o22", word: "Candado", emoji: "🔒" },
  { id: "o23", word: "Lámpara", emoji: "💡" },
  { id: "o24", word: "Reloj", emoji: "⏰" },
  { id: "o25", word: "Llave", emoji: "🔑" },
  { id: "o26", word: "Escoba", emoji: "🧹" },
  { id: "o27", word: "Balde", emoji: "🪣" },
  { id: "o28", word: "Paraguas", emoji: "☂️" },
  { id: "o29", word: "Mochila", emoji: "🎒" },
  { id: "o30", word: "Almanaque", emoji: "📅" },
  { id: "o31", word: "Radio", emoji: "📻" },
  { id: "o32", word: "Computadora", emoji: "💻" },
  { id: "o33", word: "Teléfono", emoji: "📱" },
  { id: "o34", word: "Enchufe", emoji: "🔌" },

  // ROPA
  { id: "r1", word: "Camisa", emoji: "👕" },
  { id: "r2", word: "Pantalón", emoji: "👖" },
  { id: "r3", word: "Zapato", emoji: "👟" },
  { id: "r4", word: "Gorra", emoji: "🧢" },
  { id: "r5", word: "Bufanda", emoji: "🧣" },
  { id: "r6", word: "Guantes", emoji: "🧤" },
  { id: "r7", word: "Vestido", emoji: "👗" },
  { id: "r8", word: "Medias", emoji: "🧦" },
  { id: "r9", word: "Campera", emoji: "🧥" },
  { id: "r10", word: "Anillo", emoji: "💍" },
  { id: "r11", word: "Sombrero", emoji: "🎩" },

  // DEPORTES
  { id: "d1", word: "Básquet", emoji: "🏀" },
  { id: "d2", word: "Tenis", emoji: "🎾" },
  { id: "d3", word: "Natación", emoji: "🏊" },
  { id: "d4", word: "Vóley", emoji: "🏐" },
  { id: "d5", word: "Boxeo", emoji: "🥊" },
  { id: "d6", word: "Karate", emoji: "🥋" },
  { id: "d7", word: "Ciclismo", emoji: "🚴" },
  { id: "d8", word: "Patinaje", emoji: "🛼" },
  { id: "d9", word: "Golf", emoji: "🏌️" },
  { id: "d10", word: "Surf", emoji: "🏄" },

  // MÚSICA
  { id: "m1", word: "Guitarra", emoji: "🎸" },
  { id: "m2", word: "Piano", emoji: "🎹" },
  { id: "m3", word: "Tambor", emoji: "🥁" },
  { id: "m4", word: "Violín", emoji: "🎻" },
  { id: "m5", word: "Flauta", emoji: "🪈" },
  { id: "m6", word: "Trompeta", emoji: "🎺" },
  { id: "m7", word: "Micrófono", emoji: "🎤" },
  { id: "m8", word: "Maracas", emoji: "🪇" },

  // NATURALEZA 2
  { id: "n1", word: "Viento", emoji: "💨" },
  { id: "n2", word: "Trueno", emoji: "⛈️" },
  { id: "n3", word: "Rayo", emoji: "⚡" },
  { id: "n4", word: "Arcoíris", emoji: "🌈" },
  { id: "n5", word: "Volcán", emoji: "🌋" },
  { id: "n6", word: "Desierto", emoji: "🏜️" },
  { id: "n7", word: "Bosque", emoji: "🌲" },
  { id: "n8", word: "Isla", emoji: "🏝️" },
  { id: "n9", word: "Roca", emoji: "🪨" },
  { id: "n10", word: "Estrella fugaz", emoji: "🌠" },

  // ESCUELA
  { id: "e1", word: "Lápiz", emoji: "✏️" },
  { id: "e2", word: "Tijera", emoji: "✂️" },
  { id: "e3", word: "Cuaderno", emoji: "📓" },
  { id: "e4", word: "Libro", emoji: "📖" },
  { id: "e5", word: "Pizarrón", emoji: "📝" },
  { id: "e6", word: "Regla", emoji: "📏" },
  { id: "e7", word: "Calculadora", emoji: "🧮" },
  { id: "e8", word: "Bolígrafo", emoji: "🖊️" },

  // CUERPO
  { id: "b1", word: "Mano", emoji: "✋" },
  { id: "b2", word: "Pie", emoji: "🦶" },
  { id: "b3", word: "Ojo", emoji: "👁️" },
  { id: "b4", word: "Nariz", emoji: "👃" },
  { id: "b5", word: "Oreja", emoji: "👂" },
  { id: "b6", word: "Boca", emoji: "👄" },
  { id: "b7", word: "Diente", emoji: "🦷" },
  { id: "b8", word: "Pelo", emoji: "🦱" },
  { id: "b9", word: "Corazón", emoji: "❤️" },
];
