import type { WhoAmIWord } from "./types";

export const WHO_AM_I_WORDS_ES: WhoAmIWord[] = [
  // ANIMALES
  { id: "a1", word: "Perro", emoji: "🐶" },
  { id: "a2", word: "Gato", emoji: "🐱" },
  { id: "a3", word: "Caballo", emoji: "🐴" },
  { id: "a4", word: "Vaca", emoji: "🐮" },
  { id: "a5", word: "Cerdo", emoji: "🐷" },
  { id: "a6", word: "Oveja", emoji: "🐑" },
  { id: "a7", word: "Gallina", emoji: "🐔" },
  { id: "a8", word: "Pato", emoji: "🦆" },
  { id: "a9", word: "León", emoji: "🦁" },
  { id: "a10", word: "Tigre", emoji: "🐯" },
  { id: "a11", word: "Elefante", emoji: "🐘" },
  { id: "a12", word: "Jirafa", emoji: "🦒" },
  { id: "a13", word: "Mono", emoji: "🐵" },
  { id: "a14", word: "Oso", emoji: "🐻" },
  { id: "a15", word: "Serpiente", emoji: "🐍" },
  { id: "a16", word: "Pájaro", emoji: "🐦" },
  { id: "a17", word: "Pez", emoji: "🐟" },
  { id: "a18", word: "Tiburón", emoji: "🦈" },
  { id: "a19", word: "Ballena", emoji: "🐳" },
  { id: "a20", word: "Delfín", emoji: "🐬" },

  // COMIDAS Y FRUTAS
  { id: "c1", word: "Manzana", emoji: "🍎" },
  { id: "c2", word: "Banana", emoji: "🍌" },
  { id: "c3", word: "Naranja", emoji: "🍊" },
  { id: "c4", word: "Uva", emoji: "🍇" },
  { id: "c5", word: "Fresa", emoji: "🍓" },
  { id: "c6", word: "Sandía", emoji: "🍉" },
  { id: "c7", word: "Melón", emoji: "🍈" },
  { id: "c8", word: "Limón", emoji: "🍋" },
  { id: "c9", word: "Tomate", emoji: "🍅" },
  { id: "c10", word: "Zanahoria", emoji: "🥕" },
  { id: "c11", word: "Papa", emoji: "🥔" },
  { id: "c12", word: "Cebolla", emoji: "🧅" },
  { id: "c13", word: "Lechuga", emoji: "🥬" },
  { id: "c14", word: "Hamburguesa", emoji: "🍔" },
  { id: "c15", word: "Pizza", emoji: "🍕" },
  { id: "c16", word: "Helado", emoji: "🍦" },
  { id: "c17", word: "Chocolate", emoji: "🍫" },
  { id: "c18", word: "Galleta", emoji: "🍪" },
  { id: "c19", word: "Pastel", emoji: "🎂" },
  { id: "c20", word: "Caramelo", emoji: "🍬" },

  // OBJETOS DE LA CASA
  { id: "o1", word: "Cama", emoji: "🛏️" },
  { id: "o2", word: "Silla", emoji: "🪑" },
  { id: "o3", word: "Mesa", emoji: "🍽️" },
  { id: "o4", word: "Sofá", emoji: "🛋️" },
  { id: "o5", word: "Puerta", emoji: "🚪" },
  { id: "o6", word: "Ventana", emoji: "🪟" },
  { id: "o7", word: "Televisión", emoji: "📺" },
  { id: "o8", word: "Refrigerador", emoji: "🧊" },
  { id: "o9", word: "Microondas", emoji: "⏲️" },
  { id: "o10", word: "Lavadora", emoji: "🧺" },
  { id: "o11", word: "Plato", emoji: "🍽️" },
  { id: "o12", word: "Vaso", emoji: "🥛" },
  { id: "o13", word: "Tenedor", emoji: "🍴" },
  { id: "o14", word: "Cuchara", emoji: "🥄" },
  { id: "o15", word: "Cuchillo", emoji: "🔪" },
  { id: "o16", word: "Toalla", emoji: "🧻" },
  { id: "o17", word: "Jabón", emoji: "🧼" },
  { id: "o18", word: "Cepillo de dientes", emoji: "🪥" },
  { id: "o19", word: "Peine", emoji: "💇" },
  { id: "o20", word: "Espejo", emoji: "🪞" },

  // JUGUETES, VEHICULOS Y NATURALEZA
  { id: "j1", word: "Pelota", emoji: "⚽" },
  { id: "j2", word: "Muñeca", emoji: "🪆" },
  { id: "j3", word: "Coche de juguete", emoji: "🚙" },
  { id: "j4", word: "Rompecabezas", emoji: "🧩" },
  { id: "j5", word: "Bicicleta", emoji: "🚲" },
  { id: "j6", word: "Coche", emoji: "🚗" },
  { id: "j7", word: "Avión", emoji: "✈️" },
  { id: "j8", word: "Barco", emoji: "⛵" },
  { id: "j9", word: "Tren", emoji: "🚆" },
  { id: "j10", word: "Autobús", emoji: "🚌" },
  { id: "j11", word: "Sol", emoji: "☀️" },
  { id: "j12", word: "Luna", emoji: "🌙" },
  { id: "j13", word: "Estrella", emoji: "⭐" },
  { id: "j14", word: "Nube", emoji: "☁️" },
  { id: "j15", word: "Lluvia", emoji: "🌧️" },
  { id: "j16", word: "Nieve", emoji: "❄️" },
  { id: "j17", word: "Árbol", emoji: "🌳" },
  { id: "j18", word: "Flor", emoji: "🌸" },
  { id: "j19", word: "Montaña", emoji: "⛰️" },
  { id: "j20", word: "Río", emoji: "🏞️" },
  { id: "j21", word: "Playa", emoji: "🏖️" },
  { id: "j22", word: "Rojo", emoji: "🔴" },
  { id: "j23", word: "Azul", emoji: "🔵" },
  { id: "j24", word: "Verde", emoji: "🟢" },
  { id: "j25", word: "Amarillo", emoji: "🟡" },
];
