import type { GuessWhoCharacter } from "./types";

// 32 characters designed as combinations of 6 traits — every trait is a
// literal askable yes/no question, so the distribution across values is
// deliberate content design (see tests/unit/guess-who-roster.test.ts),
// not incidental: no single trait value should be a near-instant giveaway
// or a near-useless question.
export const GUESS_WHO_CHARACTERS: GuessWhoCharacter[] = [
  {
    id: "c1",
    name: "Sofía",
    traits: {
      glasses: false,
      hat: false,
      hairColor: "pelirrojo",
      hairLength: "largo",
      facialHair: "ninguno",
      earrings: true,
    },
  },
  {
    id: "c2",
    name: "Mateo",
    traits: {
      glasses: true,
      hat: false,
      hairColor: "rubio",
      hairLength: "largo",
      facialHair: "ninguno",
      earrings: false,
    },
  },
  {
    id: "c3",
    name: "Emma",
    traits: {
      glasses: true,
      hat: true,
      hairColor: "rubio",
      hairLength: "corto",
      facialHair: "bigote",
      earrings: true,
    },
  },
  {
    id: "c4",
    name: "Lucas",
    traits: {
      glasses: false,
      hat: true,
      hairColor: "pelirrojo",
      hairLength: "calvo",
      facialHair: "ninguno",
      earrings: false,
    },
  },
  {
    id: "c5",
    name: "Valentina",
    traits: {
      glasses: true,
      hat: true,
      hairColor: "pelirrojo",
      hairLength: "corto",
      facialHair: "barba",
      earrings: true,
    },
  },
  {
    id: "c6",
    name: "Diego",
    traits: {
      glasses: true,
      hat: false,
      hairColor: "rubio",
      hairLength: "calvo",
      facialHair: "ninguno",
      earrings: true,
    },
  },
  {
    id: "c7",
    name: "Martina",
    traits: {
      glasses: false,
      hat: true,
      hairColor: "negro",
      hairLength: "corto",
      facialHair: "bigote",
      earrings: true,
    },
  },
  {
    id: "c8",
    name: "Julián",
    traits: {
      glasses: true,
      hat: false,
      hairColor: "castaño",
      hairLength: "corto",
      facialHair: "ninguno",
      earrings: false,
    },
  },
  {
    id: "c9",
    name: "Camila",
    traits: {
      glasses: true,
      hat: false,
      hairColor: "castaño",
      hairLength: "corto",
      facialHair: "bigote",
      earrings: false,
    },
  },
  {
    id: "c10",
    name: "Nicolás",
    traits: {
      glasses: false,
      hat: false,
      hairColor: "rubio",
      hairLength: "corto",
      facialHair: "bigote",
      earrings: false,
    },
  },
  {
    id: "c11",
    name: "Isabella",
    traits: {
      glasses: true,
      hat: false,
      hairColor: "negro",
      hairLength: "corto",
      facialHair: "barba",
      earrings: true,
    },
  },
  {
    id: "c12",
    name: "Santiago",
    traits: {
      glasses: false,
      hat: true,
      hairColor: "castaño",
      hairLength: "largo",
      facialHair: "barba",
      earrings: true,
    },
  },
  {
    id: "c13",
    name: "Emilia",
    traits: {
      glasses: true,
      hat: false,
      hairColor: "castaño",
      hairLength: "corto",
      facialHair: "barba",
      earrings: true,
    },
  },
  {
    id: "c14",
    name: "Sebastián",
    traits: {
      glasses: true,
      hat: true,
      hairColor: "negro",
      hairLength: "corto",
      facialHair: "bigote",
      earrings: true,
    },
  },
  {
    id: "c15",
    name: "Renata",
    traits: {
      glasses: true,
      hat: true,
      hairColor: "pelirrojo",
      hairLength: "largo",
      facialHair: "ninguno",
      earrings: true,
    },
  },
  {
    id: "c16",
    name: "Alejandro",
    traits: {
      glasses: false,
      hat: true,
      hairColor: "negro",
      hairLength: "calvo",
      facialHair: "ninguno",
      earrings: false,
    },
  },
  {
    id: "c17",
    name: "Victoria",
    traits: {
      glasses: true,
      hat: false,
      hairColor: "pelirrojo",
      hairLength: "largo",
      facialHair: "ninguno",
      earrings: true,
    },
  },
  {
    id: "c18",
    name: "Joaquín",
    traits: {
      glasses: true,
      hat: false,
      hairColor: "rubio",
      hairLength: "corto",
      facialHair: "ninguno",
      earrings: false,
    },
  },
  {
    id: "c19",
    name: "Antonella",
    traits: {
      glasses: true,
      hat: true,
      hairColor: "rubio",
      hairLength: "largo",
      facialHair: "ninguno",
      earrings: false,
    },
  },
  {
    id: "c20",
    name: "Gabriel",
    traits: {
      glasses: false,
      hat: true,
      hairColor: "negro",
      hairLength: "calvo",
      facialHair: "ninguno",
      earrings: true,
    },
  },
  {
    id: "c21",
    name: "Fernanda",
    traits: {
      glasses: true,
      hat: true,
      hairColor: "castaño",
      hairLength: "largo",
      facialHair: "bigote",
      earrings: false,
    },
  },
  {
    id: "c22",
    name: "Adrián",
    traits: {
      glasses: false,
      hat: false,
      hairColor: "rubio",
      hairLength: "corto",
      facialHair: "ninguno",
      earrings: false,
    },
  },
  {
    id: "c23",
    name: "Valeria",
    traits: {
      glasses: false,
      hat: false,
      hairColor: "castaño",
      hairLength: "corto",
      facialHair: "barba",
      earrings: false,
    },
  },
  {
    id: "c24",
    name: "Máximo",
    traits: {
      glasses: false,
      hat: false,
      hairColor: "pelirrojo",
      hairLength: "largo",
      facialHair: "ninguno",
      earrings: false,
    },
  },
  {
    id: "c25",
    name: "Daniela",
    traits: {
      glasses: false,
      hat: true,
      hairColor: "pelirrojo",
      hairLength: "calvo",
      facialHair: "bigote",
      earrings: false,
    },
  },
  {
    id: "c26",
    name: "Tomás",
    traits: {
      glasses: false,
      hat: true,
      hairColor: "castaño",
      hairLength: "largo",
      facialHair: "ninguno",
      earrings: true,
    },
  },
  {
    id: "c27",
    name: "Constanza",
    traits: {
      glasses: false,
      hat: true,
      hairColor: "negro",
      hairLength: "calvo",
      facialHair: "barba",
      earrings: false,
    },
  },
  {
    id: "c28",
    name: "Benjamín",
    traits: {
      glasses: false,
      hat: true,
      hairColor: "castaño",
      hairLength: "corto",
      facialHair: "bigote",
      earrings: true,
    },
  },
  {
    id: "c29",
    name: "Florencia",
    traits: {
      glasses: true,
      hat: false,
      hairColor: "pelirrojo",
      hairLength: "largo",
      facialHair: "barba",
      earrings: false,
    },
  },
  {
    id: "c30",
    name: "Agustín",
    traits: {
      glasses: false,
      hat: true,
      hairColor: "rubio",
      hairLength: "largo",
      facialHair: "ninguno",
      earrings: true,
    },
  },
  {
    id: "c31",
    name: "Catalina",
    traits: {
      glasses: true,
      hat: false,
      hairColor: "negro",
      hairLength: "corto",
      facialHair: "barba",
      earrings: true,
    },
  },
  {
    id: "c32",
    name: "Ignacio",
    traits: {
      glasses: false,
      hat: false,
      hairColor: "negro",
      hairLength: "largo",
      facialHair: "ninguno",
      earrings: false,
    },
  },
];
