import type { ImpostorWord } from "./types";

export const IMPOSTOR_WORDS_EN: ImpostorWord[] = [
  // ANIMALS
  { id: "a1", word: "Dog", category: "Animal", easyHint: "Loyal / Barks" },
  { id: "a2", word: "Cat", category: "Animal", easyHint: "Meow / Whiskers" },
  { id: "a3", word: "Horse", category: "Animal", easyHint: "Rides / Neighs" },
  { id: "a4", word: "Cow", category: "Animal", easyHint: "Milk / Moo" },
  { id: "a5", word: "Pig", category: "Animal", easyHint: "Pink / Oink" },
  { id: "a6", word: "Sheep", category: "Animal", easyHint: "Wool / Baa" },
  { id: "a7", word: "Hen", category: "Animal", easyHint: "Eggs / Cluck cluck" },
  { id: "a8", word: "Duck", category: "Animal", easyHint: "Water / Quack" },
  { id: "a9", word: "Lion", category: "Wild animal", easyHint: "King of the jungle" },
  { id: "a10", word: "Tiger", category: "Wild animal", easyHint: "Stripes / Fierce" },
  { id: "a11", word: "Elephant", category: "Wild animal", easyHint: "Trunk / Huge" },
  { id: "a12", word: "Giraffe", category: "Wild animal", easyHint: "Long neck" },
  { id: "a13", word: "Monkey", category: "Wild animal", easyHint: "Bananas / Trees" },
  { id: "a14", word: "Bear", category: "Wild animal", easyHint: "Honey / Hibernates" },
  { id: "a15", word: "Snake", category: "Wild animal", easyHint: "Slithers / Venom" },
  { id: "a16", word: "Bird", category: "Flying animal", easyHint: "Wings / Nest" },
  { id: "a17", word: "Fish", category: "Aquatic animal", easyHint: "Swims / Scales" },
  { id: "a18", word: "Shark", category: "Aquatic animal", easyHint: "Fin / Dangerous" },
  { id: "a19", word: "Whale", category: "Aquatic animal", easyHint: "Giant of the sea" },
  { id: "a20", word: "Dolphin", category: "Aquatic animal", easyHint: "Smart / Jumps" },

  // FOOD & FRUIT
  { id: "c1", word: "Apple", category: "Fruit", easyHint: "Red / Snow White" },
  { id: "c2", word: "Banana", category: "Fruit", easyHint: "Yellow / Monkeys" },
  { id: "c3", word: "Orange", category: "Fruit", easyHint: "Juice / Citrus" },
  { id: "c4", word: "Grape", category: "Fruit", easyHint: "Bunch / Wine" },
  { id: "c5", word: "Strawberry", category: "Fruit", easyHint: "Red / Small" },
  { id: "c6", word: "Watermelon", category: "Fruit", easyHint: "Green outside / Red inside" },
  { id: "c7", word: "Melon", category: "Fruit", easyHint: "Round / Sweet" },
  { id: "c8", word: "Lemon", category: "Fruit", easyHint: "Sour / Yellow" },
  { id: "c9", word: "Tomato", category: "Vegetable", easyHint: "Red / Salad" },
  { id: "c10", word: "Carrot", category: "Vegetable", easyHint: "Orange / Rabbit" },
  { id: "c11", word: "Potato", category: "Vegetable", easyHint: "Fries / Mash" },
  { id: "c12", word: "Onion", category: "Vegetable", easyHint: "Makes you cry" },
  { id: "c13", word: "Lettuce", category: "Vegetable", easyHint: "Green leaves" },
  { id: "c14", word: "Hamburger", category: "Food", easyHint: "Bun and meat" },
  { id: "c15", word: "Pizza", category: "Food", easyHint: "Cheese / Slices" },
  { id: "c16", word: "Ice cream", category: "Dessert", easyHint: "Cold / Cone" },
  { id: "c17", word: "Chocolate", category: "Dessert", easyHint: "Cocoa / Sweet" },
  { id: "c18", word: "Cookie", category: "Dessert", easyHint: "Oven / Chips" },
  { id: "c19", word: "Cake", category: "Dessert", easyHint: "Birthday / Candles" },
  { id: "c20", word: "Candy", category: "Sweet", easyHint: "Sugar / Wrapper" },

  // HOUSEHOLD OBJECTS
  { id: "o1", word: "Bed", category: "Furniture", easyHint: "Sleep / Mattress" },
  { id: "o2", word: "Chair", category: "Furniture", easyHint: "Sit / 4 legs" },
  { id: "o3", word: "Table", category: "Furniture", easyHint: "Eat on it" },
  { id: "o4", word: "Sofa", category: "Furniture", easyHint: "Living room / Rest" },
  { id: "o5", word: "Door", category: "Part of the house", easyHint: "Open / Close" },
  { id: "o6", word: "Window", category: "Part of the house", easyHint: "Look outside / Glass" },
  { id: "o7", word: "Television", category: "Appliance", easyHint: "Screen / Remote control" },
  { id: "o8", word: "Refrigerator", category: "Appliance", easyHint: "Keeps food cold" },
  { id: "o9", word: "Microwave", category: "Appliance", easyHint: "Heats quickly" },
  { id: "o10", word: "Washing machine", category: "Appliance", easyHint: "Cleans clothes" },
  { id: "o11", word: "Plate", category: "Kitchen utensil", easyHint: "Round / Serves food" },
  { id: "o12", word: "Glass", category: "Kitchen utensil", easyHint: "Drink water / Crystal" },
  { id: "o13", word: "Fork", category: "Kitchen utensil", easyHint: "Prongs / Eating" },
  { id: "o14", word: "Spoon", category: "Kitchen utensil", easyHint: "Soup / Dessert" },
  { id: "o15", word: "Knife", category: "Kitchen utensil", easyHint: "Cuts meat" },
  { id: "o16", word: "Towel", category: "Bathroom item", easyHint: "Dry your body" },
  { id: "o17", word: "Soap", category: "Bathroom item", easyHint: "Foam / Cleaning" },
  { id: "o18", word: "Toothbrush", category: "Bathroom item", easyHint: "Clean mouth / Paste" },
  { id: "o19", word: "Comb", category: "Bathroom item", easyHint: "Hair / Untangle" },
  { id: "o20", word: "Mirror", category: "Bathroom/bedroom item", easyHint: "Reflection" },

  // PROFESSIONS
  { id: "p1", word: "Police officer", category: "Profession", easyHint: "Blue uniform / Arrests" },
  { id: "p2", word: "Firefighter", category: "Profession", easyHint: "Puts out fire / Hose" },
  { id: "p3", word: "Doctor", category: "Profession", easyHint: "Cures the sick / Hospital" },
  { id: "p4", word: "Nurse", category: "Profession", easyHint: "Helps the doctor" },
  { id: "p5", word: "Teacher", category: "Profession", easyHint: "Teaches / School" },
  { id: "p6", word: "Astronaut", category: "Profession", easyHint: "Travels to space" },
  { id: "p7", word: "Pilot", category: "Profession", easyHint: "Flies planes" },
  { id: "p8", word: "Singer", category: "Profession", easyHint: "Microphone / Music" },
  { id: "p9", word: "Actor", category: "Profession", easyHint: "Movies / Theater" },
  { id: "p10", word: "Soccer player", category: "Sport", easyHint: "Goals / Ball" },
  { id: "p11", word: "Cook", category: "Profession", easyHint: "Prepares food / Chef" },
  { id: "p12", word: "Mail carrier", category: "Profession", easyHint: "Delivers letters" },
  { id: "p13", word: "Mechanic", category: "Profession", easyHint: "Fixes cars" },
  { id: "p14", word: "Hairdresser", category: "Profession", easyHint: "Cuts hair" },
  { id: "p15", word: "Farmer", category: "Profession", easyHint: "Tractor / Crops" },

  // TOYS, VEHICLES & NATURE
  { id: "j1", word: "Ball", category: "Toy/Sport", easyHint: "Round / Bounces" },
  { id: "j2", word: "Doll", category: "Toy", easyHint: "Playing house / Baby" },
  { id: "j3", word: "Toy car", category: "Toy", easyHint: "Small wheels" },
  { id: "j4", word: "Puzzle", category: "Game", easyHint: "Pieces / Assemble" },
  { id: "j5", word: "Bicycle", category: "Vehicle", easyHint: "Two wheels / Pedals" },
  { id: "j6", word: "Car", category: "Vehicle", easyHint: "Four wheels / Engine" },
  { id: "j7", word: "Airplane", category: "Vehicle", easyHint: "Flies / Sky" },
  { id: "j8", word: "Boat", category: "Vehicle", easyHint: "Floats / Sea" },
  { id: "j9", word: "Train", category: "Vehicle", easyHint: "Tracks / Wagons" },
  { id: "j10", word: "Bus", category: "Vehicle", easyHint: "Public transport / Passengers" },
  { id: "j11", word: "Sun", category: "Nature", easyHint: "Daytime / Yellow and hot" },
  { id: "j12", word: "Moon", category: "Nature", easyHint: "Night / White" },
  { id: "j13", word: "Star", category: "Nature", easyHint: "Shines at night" },
  { id: "j14", word: "Cloud", category: "Nature", easyHint: "White / In the sky" },
  { id: "j15", word: "Rain", category: "Nature", easyHint: "Water drops" },
  { id: "j16", word: "Snow", category: "Nature", easyHint: "Cold / White flakes" },
  { id: "j17", word: "Tree", category: "Nature", easyHint: "Trunk / Green leaves" },
  { id: "j18", word: "Flower", category: "Nature", easyHint: "Petals / Spring" },
  { id: "j19", word: "Mountain", category: "Nature", easyHint: "High peak / Climb" },
  { id: "j20", word: "River", category: "Nature", easyHint: "Flowing water" },
  { id: "j21", word: "Beach", category: "Nature", easyHint: "Sand and sea" },
  { id: "j22", word: "Red", category: "Color", easyHint: "Color of blood/fire" },
  { id: "j23", word: "Blue", category: "Color", easyHint: "Color of sky/sea" },
  { id: "j24", word: "Green", category: "Color", easyHint: "Color of grass" },
  { id: "j25", word: "Yellow", category: "Color", easyHint: "Color of the sun" },
];
