import type { ImpostorWord } from "./types";

export const IMPOSTOR_WORDS_EN: ImpostorWord[] = [
  // ANIMALS
  { id: "a1", word: "Dog", category: "Animal", easyHint: "Loyal / Barks" },
  { id: "a2", word: "Cat", category: "Animal", easyHint: "Meow / Whiskers" },
  { id: "a3", word: "Horse", category: "Animal", easyHint: "Rides / Neighs" },
  { id: "a4", word: "Cow", category: "Animal", easyHint: "Milk / Moo" },
  { id: "a5", word: "Pig", category: "Animal", easyHint: "Pink / Oink" },
  { id: "a6", word: "Sheep", category: "Animal", easyHint: "Wool / Baa" },
  { id: "a7", word: "Hen", category: "Animal", easyHint: "Eggs / Cluck cluck" },
  { id: "a8", word: "Duck", category: "Animal", easyHint: "Water / Quack" },
  { id: "a9", word: "Lion", category: "Wild animal", easyHint: "King of the jungle" },
  { id: "a10", word: "Tiger", category: "Wild animal", easyHint: "Stripes / Fierce" },
  { id: "a11", word: "Elephant", category: "Wild animal", easyHint: "Trunk / Huge" },
  { id: "a12", word: "Giraffe", category: "Wild animal", easyHint: "Long neck" },
  { id: "a13", word: "Monkey", category: "Wild animal", easyHint: "Bananas / Trees" },
  { id: "a14", word: "Bear", category: "Wild animal", easyHint: "Honey / Hibernates" },
  { id: "a15", word: "Snake", category: "Wild animal", easyHint: "Slithers / Venom" },
  { id: "a16", word: "Bird", category: "Flying animal", easyHint: "Wings / Nest" },
  { id: "a17", word: "Fish", category: "Aquatic animal", easyHint: "Swims / Scales" },
  { id: "a18", word: "Shark", category: "Aquatic animal", easyHint: "Fin / Dangerous" },
  { id: "a19", word: "Whale", category: "Aquatic animal", easyHint: "Giant of the sea" },
  { id: "a20", word: "Dolphin", category: "Aquatic animal", easyHint: "Smart / Jumps" },

  // FOOD & FRUIT
  { id: "c1", word: "Apple", category: "Fruit", easyHint: "Red / Snow White" },
  { id: "c2", word: "Banana", category: "Fruit", easyHint: "Yellow / Monkeys" },
  { id: "c3", word: "Orange", category: "Fruit", easyHint: "Juice / Citrus" },
  { id: "c4", word: "Grape", category: "Fruit", easyHint: "Bunch / Wine" },
  { id: "c5", word: "Strawberry", category: "Fruit", easyHint: "Red / Small" },
  { id: "c6", word: "Watermelon", category: "Fruit", easyHint: "Green outside / Red inside" },
  { id: "c7", word: "Melon", category: "Fruit", easyHint: "Round / Sweet" },
  { id: "c8", word: "Lemon", category: "Fruit", easyHint: "Sour / Yellow" },
  { id: "c9", word: "Tomato", category: "Vegetable", easyHint: "Red / Salad" },
  { id: "c10", word: "Carrot", category: "Vegetable", easyHint: "Orange / Rabbit" },
  { id: "c11", word: "Potato", category: "Vegetable", easyHint: "Fries / Mash" },
  { id: "c12", word: "Onion", category: "Vegetable", easyHint: "Makes you cry" },
  { id: "c13", word: "Lettuce", category: "Vegetable", easyHint: "Green leaves" },
  { id: "c14", word: "Hamburger", category: "Food", easyHint: "Bun and meat" },
  { id: "c15", word: "Pizza", category: "Food", easyHint: "Cheese / Slices" },
  { id: "c16", word: "Ice cream", category: "Dessert", easyHint: "Cold / Cone" },
  { id: "c17", word: "Chocolate", category: "Dessert", easyHint: "Cocoa / Sweet" },
  { id: "c18", word: "Cookie", category: "Dessert", easyHint: "Oven / Chips" },
  { id: "c19", word: "Cake", category: "Dessert", easyHint: "Birthday / Candles" },
  { id: "c20", word: "Candy", category: "Sweet", easyHint: "Sugar / Wrapper" },

  // HOUSEHOLD OBJECTS
  { id: "o1", word: "Bed", category: "Furniture", easyHint: "Sleep / Mattress" },
  { id: "o2", word: "Chair", category: "Furniture", easyHint: "Sit / 4 legs" },
  { id: "o3", word: "Table", category: "Furniture", easyHint: "Eat on it" },
  { id: "o4", word: "Sofa", category: "Furniture", easyHint: "Living room / Rest" },
  { id: "o5", word: "Door", category: "Part of the house", easyHint: "Open / Close" },
  { id: "o6", word: "Window", category: "Part of the house", easyHint: "Look outside / Glass" },
  { id: "o7", word: "Television", category: "Appliance", easyHint: "Screen / Remote control" },
  { id: "o8", word: "Refrigerator", category: "Appliance", easyHint: "Keeps food cold" },
  { id: "o9", word: "Microwave", category: "Appliance", easyHint: "Heats quickly" },
  { id: "o10", word: "Washing machine", category: "Appliance", easyHint: "Cleans clothes" },
  { id: "o11", word: "Plate", category: "Kitchen utensil", easyHint: "Round / Serves food" },
  { id: "o12", word: "Glass", category: "Kitchen utensil", easyHint: "Drink water / Crystal" },
  { id: "o13", word: "Fork", category: "Kitchen utensil", easyHint: "Prongs / Eating" },
  { id: "o14", word: "Spoon", category: "Kitchen utensil", easyHint: "Soup / Dessert" },
  { id: "o15", word: "Knife", category: "Kitchen utensil", easyHint: "Cuts meat" },
  { id: "o16", word: "Towel", category: "Bathroom item", easyHint: "Dry your body" },
  { id: "o17", word: "Soap", category: "Bathroom item", easyHint: "Foam / Cleaning" },
  { id: "o18", word: "Toothbrush", category: "Bathroom item", easyHint: "Clean mouth / Paste" },
  { id: "o19", word: "Comb", category: "Bathroom item", easyHint: "Hair / Untangle" },
  { id: "o20", word: "Mirror", category: "Bathroom/bedroom item", easyHint: "Reflection" },

  // PROFESSIONS
  { id: "p1", word: "Police officer", category: "Profession", easyHint: "Blue uniform / Arrests" },
  { id: "p2", word: "Firefighter", category: "Profession", easyHint: "Puts out fire / Hose" },
  { id: "p3", word: "Doctor", category: "Profession", easyHint: "Cures the sick / Hospital" },
  { id: "p4", word: "Nurse", category: "Profession", easyHint: "Helps the doctor" },
  { id: "p5", word: "Teacher", category: "Profession", easyHint: "Teaches / School" },
  { id: "p6", word: "Astronaut", category: "Profession", easyHint: "Travels to space" },
  { id: "p7", word: "Pilot", category: "Profession", easyHint: "Flies planes" },
  { id: "p8", word: "Singer", category: "Profession", easyHint: "Microphone / Music" },
  { id: "p9", word: "Actor", category: "Profession", easyHint: "Movies / Theater" },
  { id: "p10", word: "Soccer player", category: "Sport", easyHint: "Goals / Ball" },
  { id: "p11", word: "Cook", category: "Profession", easyHint: "Prepares food / Chef" },
  { id: "p12", word: "Mail carrier", category: "Profession", easyHint: "Delivers letters" },
  { id: "p13", word: "Mechanic", category: "Profession", easyHint: "Fixes cars" },
  { id: "p14", word: "Hairdresser", category: "Profession", easyHint: "Cuts hair" },
  { id: "p15", word: "Farmer", category: "Profession", easyHint: "Tractor / Crops" },

  // TOYS, VEHICLES & NATURE
  { id: "j1", word: "Ball", category: "Toy/Sport", easyHint: "Round / Bounces" },
  { id: "j2", word: "Doll", category: "Toy", easyHint: "Playing house / Baby" },
  { id: "j3", word: "Toy car", category: "Toy", easyHint: "Small wheels" },
  { id: "j4", word: "Puzzle", category: "Game", easyHint: "Pieces / Assemble" },
  { id: "j5", word: "Bicycle", category: "Vehicle", easyHint: "Two wheels / Pedals" },
  { id: "j6", word: "Car", category: "Vehicle", easyHint: "Four wheels / Engine" },
  { id: "j7", word: "Airplane", category: "Vehicle", easyHint: "Flies / Sky" },
  { id: "j8", word: "Boat", category: "Vehicle", easyHint: "Floats / Sea" },
  { id: "j9", word: "Train", category: "Vehicle", easyHint: "Tracks / Wagons" },
  { id: "j10", word: "Bus", category: "Vehicle", easyHint: "Public transport / Passengers" },
  { id: "j11", word: "Sun", category: "Nature", easyHint: "Daytime / Yellow and hot" },
  { id: "j12", word: "Moon", category: "Nature", easyHint: "Night / White" },
  { id: "j13", word: "Star", category: "Nature", easyHint: "Shines at night" },
  { id: "j14", word: "Cloud", category: "Nature", easyHint: "White / In the sky" },
  { id: "j15", word: "Rain", category: "Nature", easyHint: "Water drops" },
  { id: "j16", word: "Snow", category: "Nature", easyHint: "Cold / White flakes" },
  { id: "j17", word: "Tree", category: "Nature", easyHint: "Trunk / Green leaves" },
  { id: "j18", word: "Flower", category: "Nature", easyHint: "Petals / Spring" },
  { id: "j19", word: "Mountain", category: "Nature", easyHint: "High peak / Climb" },
  { id: "j20", word: "River", category: "Nature", easyHint: "Flowing water" },
  { id: "j21", word: "Beach", category: "Nature", easyHint: "Sand and sea" },
  { id: "j22", word: "Red", category: "Color", easyHint: "Color of blood/fire" },
  { id: "j23", word: "Blue", category: "Color", easyHint: "Color of sky/sea" },
  { id: "j24", word: "Green", category: "Color", easyHint: "Color of grass" },
  { id: "j25", word: "Yellow", category: "Color", easyHint: "Color of the sun" },

  // ANIMALS 2
  { id: "a21", word: "Bee", category: "Insect", easyHint: "Yellow and black / Makes honey" },
  { id: "a22", word: "Butterfly", category: "Insect", easyHint: "Colorful wings" },
  { id: "a23", word: "Ant", category: "Insect", easyHint: "Tiny / Very strong" },
  { id: "a24", word: "Spider", category: "Animal", easyHint: "Eight legs / Spins webs" },
  { id: "a25", word: "Frog", category: "Animal", easyHint: "Jumps / Lives in water and on land" },
  { id: "a26", word: "Turtle", category: "Animal", easyHint: "Slow / Shell" },
  { id: "a27", word: "Rabbit", category: "Animal", easyHint: "Long ears / Hops" },
  { id: "a28", word: "Squirrel", category: "Animal", easyHint: "Fluffy tail / Gathers nuts" },
  { id: "a29", word: "Fox", category: "Wild animal", easyHint: "Sly / Fluffy tail" },
  { id: "a30", word: "Wolf", category: "Wild animal", easyHint: "Howls / Lives in a pack" },
  { id: "a31", word: "Zebra", category: "Wild animal", easyHint: "Black and white stripes" },
  { id: "a32", word: "Kangaroo", category: "Wild animal", easyHint: "Hops / Pouch on its belly" },
  { id: "a33", word: "Koala", category: "Wild animal", easyHint: "Sleeps a lot / Eats eucalyptus" },
  { id: "a34", word: "Owl", category: "Flying animal", easyHint: "Big eyes / Flies at night" },
  { id: "a35", word: "Penguin", category: "Animal", easyHint: "Lives in the cold / Can't fly but swims" },

  // FOOD 2
  { id: "c21", word: "Bread", category: "Food", easyHint: "Baked / Eaten with butter" },
  { id: "c22", word: "Cheese", category: "Food", easyHint: "Yellow / Comes from milk" },
  { id: "c23", word: "Egg", category: "Food", easyHint: "White outside / Yellow inside" },
  { id: "c24", word: "Milk", category: "Drink", easyHint: "White / Comes from a cow" },
  { id: "c25", word: "Juice", category: "Drink", easyHint: "From fruit / You drink it" },
  { id: "c26", word: "Soup", category: "Food", easyHint: "Hot / Eaten with a spoon" },
  { id: "c27", word: "Salad", category: "Food", easyHint: "Vegetables / Eaten cold" },
  { id: "c28", word: "Rice", category: "Food", easyHint: "White / Tiny grains" },
  { id: "c29", word: "Noodles", category: "Food", easyHint: "Long / With sauce" },
  { id: "c30", word: "Chicken", category: "Food", easyHint: "Bird / Breast meat" },
  { id: "c31", word: "Seafood", category: "Food", easyHint: "From the sea / Has bones" },
  { id: "c32", word: "Honey", category: "Food", easyHint: "Sweet / Made by bees" },
  { id: "c33", word: "Jam", category: "Food", easyHint: "Sweet / Comes in jars" },
  { id: "c34", word: "Popcorn", category: "Food", easyHint: "From the movies / Pops when heated" },
  { id: "c35", word: "Mate tea", category: "Drink", easyHint: "Drunk through a metal straw" },

  // HOME 2
  { id: "o21", word: "Candle", category: "Household item", easyHint: "Gives light / Blown out" },
  { id: "o22", word: "Padlock", category: "Household item", easyHint: "Locks with a key" },
  { id: "o23", word: "Lamp", category: "Household item", easyHint: "Gives light" },
  { id: "o24", word: "Clock", category: "Household item", easyHint: "Tells the time" },
  { id: "o25", word: "Key", category: "Household item", easyHint: "Opens doors" },
  { id: "o26", word: "Broom", category: "Household item", easyHint: "Sweeps the floor" },
  { id: "o27", word: "Bucket", category: "Household item", easyHint: "Holds water / Cleaning" },
  { id: "o28", word: "Umbrella", category: "Household item", easyHint: "For the rain / Opens up" },
  { id: "o29", word: "Backpack", category: "Household item", easyHint: "Carried on your back" },
  { id: "o30", word: "Calendar", category: "Household item", easyHint: "Shows the days and months" },
  { id: "o31", word: "Radio", category: "Appliance", easyHint: "You listen to music on it" },
  { id: "o32", word: "Computer", category: "Appliance", easyHint: "Screen and keyboard" },
  { id: "o33", word: "Phone", category: "Appliance", easyHint: "For calling" },
  { id: "o34", word: "Plug", category: "Household item", easyHint: "Where electricity connects" },

  // CLOTHES
  { id: "r1", word: "Shirt", category: "Clothing", easyHint: "Has buttons and sleeves" },
  { id: "r2", word: "Pants", category: "Clothing", easyHint: "Worn on both legs" },
  { id: "r3", word: "Shoe", category: "Clothing", easyHint: "Worn on your foot / Has laces" },
  { id: "r4", word: "Cap", category: "Clothing", easyHint: "Worn on your head / Has a brim" },
  { id: "r5", word: "Scarf", category: "Clothing", easyHint: "Worn around the neck / For the cold" },
  { id: "r6", word: "Gloves", category: "Clothing", easyHint: "Worn on your hands / For the cold" },
  { id: "r7", word: "Dress", category: "Clothing", easyHint: "Long skirt" },
  { id: "r8", word: "Socks", category: "Clothing", easyHint: "Worn under your shoes" },
  { id: "r9", word: "Jacket", category: "Clothing", easyHint: "Keeps you warm" },
  { id: "r10", word: "Belt", category: "Clothing", easyHint: "Holds up your pants" },
  { id: "r11", word: "Hat", category: "Clothing", easyHint: "Worn on your head" },

  // SPORTS
  { id: "d1", word: "Basketball", category: "Sport", easyHint: "Hoop / Orange ball" },
  { id: "d2", word: "Tennis", category: "Sport", easyHint: "Racket / Court" },
  { id: "d3", word: "Swimming", category: "Sport", easyHint: "In the water / Pool" },
  { id: "d4", word: "Volleyball", category: "Sport", easyHint: "Net / Ball" },
  { id: "d5", word: "Boxing", category: "Sport", easyHint: "Gloves / Punches" },
  { id: "d6", word: "Karate", category: "Sport", easyHint: "Colored belt / Kicks" },
  { id: "d7", word: "Cycling", category: "Sport", easyHint: "On a bike / Race" },
  { id: "d8", word: "Skating", category: "Sport", easyHint: "Wheels or ice" },
  { id: "d9", word: "Golf", category: "Sport", easyHint: "Club / Small ball" },
  { id: "d10", word: "Surfing", category: "Sport", easyHint: "Board / Waves" },

  // MUSIC
  { id: "m1", word: "Guitar", category: "Instrument", easyHint: "Strings / Strummed" },
  { id: "m2", word: "Piano", category: "Instrument", easyHint: "Black and white keys" },
  { id: "m3", word: "Drum", category: "Instrument", easyHint: "Hit / Makes rhythm" },
  { id: "m4", word: "Violin", category: "Instrument", easyHint: "Strings / Played with a bow" },
  { id: "m5", word: "Flute", category: "Instrument", easyHint: "Blown / Has little holes" },
  { id: "m6", word: "Trumpet", category: "Instrument", easyHint: "Blown / Made of metal" },
  { id: "m7", word: "Microphone", category: "Instrument", easyHint: "Used for singing" },
  { id: "m8", word: "Maracas", category: "Instrument", easyHint: "Shaken / Make a sound" },

  // NATURE 2
  { id: "n1", word: "Wind", category: "Nature", easyHint: "Moves the leaves" },
  { id: "n2", word: "Thunder", category: "Nature", easyHint: "Loud noise in a storm" },
  { id: "n3", word: "Lightning", category: "Nature", easyHint: "Light in the sky / Storm" },
  { id: "n4", word: "Rainbow", category: "Nature", easyHint: "Colors in the sky / After the rain" },
  { id: "n5", word: "Volcano", category: "Nature", easyHint: "Lava / Eruption" },
  { id: "n6", word: "Desert", category: "Nature", easyHint: "Sand / Very hot" },
  { id: "n7", word: "Forest", category: "Nature", easyHint: "Lots of trees together" },
  { id: "n8", word: "Island", category: "Nature", easyHint: "Land surrounded by water" },
  { id: "n9", word: "Rock", category: "Nature", easyHint: "Hard / Made of stone" },
  { id: "n10", word: "Shooting star", category: "Nature", easyHint: "Crosses the night sky" },

  // SCHOOL
  { id: "e1", word: "Pencil", category: "School supply", easyHint: "For writing / Can be erased" },
  { id: "e2", word: "Scissors", category: "School supply", easyHint: "For cutting paper" },
  { id: "e3", word: "Notebook", category: "School supply", easyHint: "Pages for writing" },
  { id: "e4", word: "Book", category: "School supply", easyHint: "Has pages to read" },
  { id: "e5", word: "Blackboard", category: "School supply", easyHint: "The teacher writes on it" },
  { id: "e6", word: "Ruler", category: "School supply", easyHint: "For measuring / Straight lines" },
  { id: "e7", word: "Calculator", category: "School supply", easyHint: "For doing math" },
  { id: "e8", word: "Pen", category: "School supply", easyHint: "Writes with ink" },

  // BODY
  { id: "b1", word: "Hand", category: "Body", easyHint: "Has fingers / Grabs things" },
  { id: "b2", word: "Foot", category: "Body", easyHint: "Used for walking" },
  { id: "b3", word: "Eye", category: "Body", easyHint: "Used for seeing" },
  { id: "b4", word: "Nose", category: "Body", easyHint: "Used for smelling" },
  { id: "b5", word: "Ear", category: "Body", easyHint: "Used for hearing" },
  { id: "b6", word: "Mouth", category: "Body", easyHint: "Used for talking and eating" },
  { id: "b7", word: "Tooth", category: "Body", easyHint: "White / Used for biting" },
  { id: "b8", word: "Hair", category: "Body", easyHint: "On your head / Gets combed" },
  { id: "b9", word: "Heart", category: "Body", easyHint: "Beats / Pumps blood" },
];
