import type { ImpostorWord } from "./types";

export const IMPOSTOR_WORDS_ES: ImpostorWord[] = [
  // ANIMALES
  { id: "a1", word: "Perro", category: "Animal", easyHint: "Fiel / Ladra" },
  { id: "a2", word: "Gato", category: "Animal", easyHint: "Miau / Araña" },
  { id: "a3", word: "Caballo", category: "Animal", easyHint: "Cabalgar / Relincha" },
  { id: "a4", word: "Vaca", category: "Animal", easyHint: "Leche / Muu" },
  { id: "a5", word: "Cerdo", category: "Animal", easyHint: "Rosa / Oink" },
  { id: "a6", word: "Oveja", category: "Animal", easyHint: "Lana / Bee" },
  { id: "a7", word: "Gallina", category: "Animal", easyHint: "Huevos / Clo clo" },
  { id: "a8", word: "Pato", category: "Animal", easyHint: "Agua / Cuac" },
  { id: "a9", word: "León", category: "Animal salvaje", easyHint: "Rey de la selva" },
  { id: "a10", word: "Tigre", category: "Animal salvaje", easyHint: "Rayas / Feroz" },
  { id: "a11", word: "Elefante", category: "Animal salvaje", easyHint: "Trompa / Grande" },
  { id: "a12", word: "Jirafa", category: "Animal salvaje", easyHint: "Cuello largo" },
  { id: "a13", word: "Mono", category: "Animal salvaje", easyHint: "Bananas / Árboles" },
  { id: "a14", word: "Oso", category: "Animal salvaje", easyHint: "Miel / Hiberna" },
  { id: "a15", word: "Serpiente", category: "Animal salvaje", easyHint: "Repta / Veneno" },
  { id: "a16", word: "Pájaro", category: "Animal volador", easyHint: "Alas / Nido" },
  { id: "a17", word: "Pez", category: "Animal acuático", easyHint: "Nada / Escamas" },
  { id: "a18", word: "Tiburón", category: "Animal acuático", easyHint: "Aleta / Peligroso" },
  { id: "a19", word: "Ballena", category: "Animal acuático", easyHint: "Gigante marino" },
  { id: "a20", word: "Delfín", category: "Animal acuático", easyHint: "Inteligente / Salta" },

  // COMIDAS Y FRUTAS
  { id: "c1", word: "Manzana", category: "Fruta", easyHint: "Roja / Blancanieves" },
  { id: "c2", word: "Banana", category: "Fruta", easyHint: "Amarilla / Monos" },
  { id: "c3", word: "Naranja", category: "Fruta", easyHint: "Jugo / Cítrico" },
  { id: "c4", word: "Uva", category: "Fruta", easyHint: "Racimo / Vino" },
  { id: "c5", word: "Fresa", category: "Fruta", easyHint: "Roja / Pequeña" },
  { id: "c6", word: "Sandía", category: "Fruta", easyHint: "Verde por fuera / Roja por dentro" },
  { id: "c7", word: "Melón", category: "Fruta", easyHint: "Redondo / Dulce" },
  { id: "c8", word: "Limón", category: "Fruta", easyHint: "Ácido / Amarillo" },
  { id: "c9", word: "Tomate", category: "Verdura", easyHint: "Rojo / Ensalada" },
  { id: "c10", word: "Zanahoria", category: "Verdura", easyHint: "Naranja / Conejo" },
  { id: "c11", word: "Papa", category: "Verdura", easyHint: "Fritas / Puré" },
  { id: "c12", word: "Cebolla", category: "Verdura", easyHint: "Hace llorar" },
  { id: "c13", word: "Lechuga", category: "Verdura", easyHint: "Hojas verdes" },
  { id: "c14", word: "Hamburguesa", category: "Comida", easyHint: "Pan y carne" },
  { id: "c15", word: "Pizza", category: "Comida", easyHint: "Queso / Porciones" },
  { id: "c16", word: "Helado", category: "Postre", easyHint: "Frío / Cono" },
  { id: "c17", word: "Chocolate", category: "Postre", easyHint: "Cacao / Dulce" },
  { id: "c18", word: "Galleta", category: "Postre", easyHint: "Horno / Chips" },
  { id: "c19", word: "Pastel", category: "Postre", easyHint: "Cumpleaños / Velas" },
  { id: "c20", word: "Caramelo", category: "Dulce", easyHint: "Azúcar / Envoltorio" },

  // OBJETOS DE LA CASA
  { id: "o1", word: "Cama", category: "Mueble", easyHint: "Dormir / Colchón" },
  { id: "o2", word: "Silla", category: "Mueble", easyHint: "Sentarse / 4 patas" },
  { id: "o3", word: "Mesa", category: "Mueble", easyHint: "Comer sobre ella" },
  { id: "o4", word: "Sofá", category: "Mueble", easyHint: "Living / Descanso" },
  { id: "o5", word: "Puerta", category: "Parte de la casa", easyHint: "Abrir / Cerrar" },
  { id: "o6", word: "Ventana", category: "Parte de la casa", easyHint: "Mirar afuera / Vidrio" },
  { id: "o7", word: "Televisión", category: "Electrodoméstico", easyHint: "Pantalla / Control remoto" },
  { id: "o8", word: "Refrigerador", category: "Electrodoméstico", easyHint: "Enfría la comida" },
  { id: "o9", word: "Microondas", category: "Electrodoméstico", easyHint: "Calienta rápido" },
  { id: "o10", word: "Lavadora", category: "Electrodoméstico", easyHint: "Limpia la ropa" },
  { id: "o11", word: "Plato", category: "Utensilio de cocina", easyHint: "Redondo / Servir comida" },
  { id: "o12", word: "Vaso", category: "Utensilio de cocina", easyHint: "Beber agua / Cristal" },
  { id: "o13", word: "Tenedor", category: "Utensilio de cocina", easyHint: "Pinchos / Comer" },
  { id: "o14", word: "Cuchara", category: "Utensilio de cocina", easyHint: "Sopa / Postre" },
  { id: "o15", word: "Cuchillo", category: "Utensilio de cocina", easyHint: "Cortar carne" },
  { id: "o16", word: "Toalla", category: "Cosa del baño", easyHint: "Secarse el cuerpo" },
  { id: "o17", word: "Jabón", category: "Cosa del baño", easyHint: "Espuma / Limpieza" },
  { id: "o18", word: "Cepillo de dientes", category: "Cosa del baño", easyHint: "Boca limpia / Pasta" },
  { id: "o19", word: "Peine", category: "Cosa del baño", easyHint: "Pelo / Desenredar" },
  { id: "o20", word: "Espejo", category: "Cosa del baño/habitación", easyHint: "Reflejo" },

  // PROFESIONES
  { id: "p1", word: "Policía", category: "Profesión", easyHint: "Uniforme azul / Arresta" },
  { id: "p2", word: "Bombero", category: "Profesión", easyHint: "Apaga fuego / Manguera" },
  { id: "p3", word: "Médico", category: "Profesión", easyHint: "Cura enfermos / Hospital" },
  { id: "p4", word: "Enfermera", category: "Profesión", easyHint: "Ayuda al doctor" },
  { id: "p5", word: "Profesor", category: "Profesión", easyHint: "Enseña / Escuela" },
  { id: "p6", word: "Astronauta", category: "Profesión", easyHint: "Viaja al espacio" },
  { id: "p7", word: "Piloto", category: "Profesión", easyHint: "Vuela aviones" },
  { id: "p8", word: "Cantante", category: "Profesión", easyHint: "Micrófono / Música" },
  { id: "p9", word: "Actor", category: "Profesión", easyHint: "Películas / Teatro" },
  { id: "p10", word: "Futbolista", category: "Deporte", easyHint: "Goles / Balón" },
  { id: "p11", word: "Cocinero", category: "Profesión", easyHint: "Prepara comida / Chef" },
  { id: "p12", word: "Cartero", category: "Profesión", easyHint: "Entrega cartas" },
  { id: "p13", word: "Mecánico", category: "Profesión", easyHint: "Arregla autos" },
  { id: "p14", word: "Peluquero", category: "Profesión", easyHint: "Corta el pelo" },
  { id: "p15", word: "Granjero", category: "Profesión", easyHint: "Tractor / Cultivos" },

  // JUGUETES, VEHICULOS Y NATURALEZA
  { id: "j1", word: "Pelota", category: "Juguete/Deporte", easyHint: "Redonda / Rebota" },
  { id: "j2", word: "Muñeca", category: "Juguete", easyHint: "Jugar a casita / Bebé" },
  { id: "j3", word: "Coche de juguete", category: "Juguete", easyHint: "Ruedas pequeñas" },
  { id: "j4", word: "Rompecabezas", category: "Juego", easyHint: "Piezas / Armar" },
  { id: "j5", word: "Bicicleta", category: "Vehículo", easyHint: "Dos ruedas / Pedales" },
  { id: "j6", word: "Coche", category: "Vehículo", easyHint: "Cuatro ruedas / Motor" },
  { id: "j7", word: "Avión", category: "Vehículo", easyHint: "Vuela / Cielo" },
  { id: "j8", word: "Barco", category: "Vehículo", easyHint: "Flota / Mar" },
  { id: "j9", word: "Tren", category: "Vehículo", easyHint: "Vías / Vagones" },
  { id: "j10", word: "Autobús", category: "Vehículo", easyHint: "Transporte público / Pasajeros" },
  { id: "j11", word: "Sol", category: "Naturaleza", easyHint: "Día / Amarillo y caliente" },
  { id: "j12", word: "Luna", category: "Naturaleza", easyHint: "Noche / Blanca" },
  { id: "j13", word: "Estrella", category: "Naturaleza", easyHint: "Brilla de noche" },
  { id: "j14", word: "Nube", category: "Naturaleza", easyHint: "Blanca / En el cielo" },
  { id: "j15", word: "Lluvia", category: "Naturaleza", easyHint: "Gotas de agua" },
  { id: "j16", word: "Nieve", category: "Naturaleza", easyHint: "Fría / Copos blancos" },
  { id: "j17", word: "Árbol", category: "Naturaleza", easyHint: "Tronco / Hojas verdes" },
  { id: "j18", word: "Flor", category: "Naturaleza", easyHint: "Pétalos / Primavera" },
  { id: "j19", word: "Montaña", category: "Naturaleza", easyHint: "Pico alto / Escalar" },
  { id: "j20", word: "Río", category: "Naturaleza", easyHint: "Agua que fluye" },
  { id: "j21", word: "Playa", category: "Naturaleza", easyHint: "Arena y mar" },
  { id: "j22", word: "Rojo", category: "Color", easyHint: "Color de la sangre/fuego" },
  { id: "j23", word: "Azul", category: "Color", easyHint: "Color del cielo/mar" },
  { id: "j24", word: "Verde", category: "Color", easyHint: "Color del pasto" },
  { id: "j25", word: "Amarillo", category: "Color", easyHint: "Color del sol" },

  // ANIMALES 2
  { id: "a21", word: "Abeja", category: "Insecto", easyHint: "Amarilla y negra / Hace miel" },
  { id: "a22", word: "Mariposa", category: "Insecto", easyHint: "Alas de colores" },
  { id: "a23", word: "Hormiga", category: "Insecto", easyHint: "Chiquita / Muy fuerte" },
  { id: "a24", word: "Araña", category: "Animal", easyHint: "Ocho patas / Teje telarañas" },
  { id: "a25", word: "Rana", category: "Animal", easyHint: "Salta / Vive en el agua y la tierra" },
  { id: "a26", word: "Tortuga", category: "Animal", easyHint: "Lenta / Caparazón" },
  { id: "a27", word: "Conejo", category: "Animal", easyHint: "Orejas largas / Salta" },
  { id: "a28", word: "Ardilla", category: "Animal", easyHint: "Cola peluda / Junta nueces" },
  { id: "a29", word: "Zorro", category: "Animal salvaje", easyHint: "Astuto / Cola peluda" },
  { id: "a30", word: "Lobo", category: "Animal salvaje", easyHint: "Aúlla / Vive en manada" },
  { id: "a31", word: "Cebra", category: "Animal salvaje", easyHint: "Rayas blancas y negras" },
  { id: "a32", word: "Canguro", category: "Animal salvaje", easyHint: "Salta / Bolsa en la panza" },
  { id: "a33", word: "Koala", category: "Animal salvaje", easyHint: "Duerme mucho / Come eucalipto" },
  { id: "a34", word: "Búho", category: "Animal volador", easyHint: "Ojos grandes / Vuela de noche" },
  { id: "a35", word: "Pingüino", category: "Animal", easyHint: "Vive en el frío / No vuela pero nada" },

  // COMIDA 2
  { id: "c21", word: "Pan", category: "Comida", easyHint: "Se hornea / Se come con manteca" },
  { id: "c22", word: "Queso", category: "Comida", easyHint: "Amarillo / Viene de la leche" },
  { id: "c23", word: "Huevo", category: "Comida", easyHint: "Blanco por fuera / Amarillo por dentro" },
  { id: "c24", word: "Leche", category: "Bebida", easyHint: "Blanca / Viene de la vaca" },
  { id: "c25", word: "Jugo", category: "Bebida", easyHint: "De frutas / Se toma" },
  { id: "c26", word: "Sopa", category: "Comida", easyHint: "Caliente / Se come con cuchara" },
  { id: "c27", word: "Ensalada", category: "Comida", easyHint: "Verduras / Se come fría" },
  { id: "c28", word: "Arroz", category: "Comida", easyHint: "Blanco / Granitos" },
  { id: "c29", word: "Fideos", category: "Comida", easyHint: "Largos / Con salsa" },
  { id: "c30", word: "Pollo", category: "Comida", easyHint: "Ave / Pechuga" },
  { id: "c31", word: "Pescado", category: "Comida", easyHint: "Viene del mar / Tiene espinas" },
  { id: "c32", word: "Miel", category: "Comida", easyHint: "Dulce / La hacen las abejas" },
  { id: "c33", word: "Mermelada", category: "Comida", easyHint: "Dulce / Va en frascos" },
  { id: "c34", word: "Pochoclo", category: "Comida", easyHint: "Del cine / Salta al calentarse" },
  { id: "c35", word: "Mate", category: "Bebida", easyHint: "Se toma con bombilla" },

  // CASA 2
  { id: "o21", word: "Vela", category: "Cosa de la casa", easyHint: "Da luz / Se apaga soplando" },
  { id: "o22", word: "Candado", category: "Cosa de la casa", easyHint: "Cierra con llave" },
  { id: "o23", word: "Lámpara", category: "Cosa de la casa", easyHint: "Da luz" },
  { id: "o24", word: "Reloj", category: "Cosa de la casa", easyHint: "Marca la hora" },
  { id: "o25", word: "Llave", category: "Cosa de la casa", easyHint: "Abre puertas" },
  { id: "o26", word: "Escoba", category: "Cosa de la casa", easyHint: "Barre el piso" },
  { id: "o27", word: "Balde", category: "Cosa de la casa", easyHint: "Para agua / Limpieza" },
  { id: "o28", word: "Paraguas", category: "Cosa de la casa", easyHint: "Para la lluvia / Se abre" },
  { id: "o29", word: "Mochila", category: "Cosa de la casa", easyHint: "Se lleva en la espalda" },
  { id: "o30", word: "Almanaque", category: "Cosa de la casa", easyHint: "Muestra los días y meses" },
  { id: "o31", word: "Radio", category: "Electrodoméstico", easyHint: "Se escucha música" },
  { id: "o32", word: "Computadora", category: "Electrodoméstico", easyHint: "Pantalla y teclado" },
  { id: "o33", word: "Teléfono", category: "Electrodoméstico", easyHint: "Para llamar" },
  { id: "o34", word: "Enchufe", category: "Cosa de la casa", easyHint: "Ahí se conecta la electricidad" },

  // ROPA
  { id: "r1", word: "Camisa", category: "Ropa", easyHint: "Tiene botones y mangas" },
  { id: "r2", word: "Pantalón", category: "Ropa", easyHint: "Se pone en las dos piernas" },
  { id: "r3", word: "Zapato", category: "Ropa", easyHint: "Va en el pie / Tiene cordones" },
  { id: "r4", word: "Gorra", category: "Ropa", easyHint: "Va en la cabeza / Tiene visera" },
  { id: "r5", word: "Bufanda", category: "Ropa", easyHint: "Va en el cuello / Para el frío" },
  { id: "r6", word: "Guantes", category: "Ropa", easyHint: "Van en las manos / Para el frío" },
  { id: "r7", word: "Vestido", category: "Ropa", easyHint: "Falda larga" },
  { id: "r8", word: "Medias", category: "Ropa", easyHint: "Van debajo del zapato" },
  { id: "r9", word: "Campera", category: "Ropa", easyHint: "Abriga del frío" },
  { id: "r10", word: "Cinturón", category: "Ropa", easyHint: "Sostiene el pantalón" },
  { id: "r11", word: "Sombrero", category: "Ropa", easyHint: "Va en la cabeza" },

  // DEPORTES
  { id: "d1", word: "Básquet", category: "Deporte", easyHint: "Aro / Pelota naranja" },
  { id: "d2", word: "Tenis", category: "Deporte", easyHint: "Raqueta / Cancha" },
  { id: "d3", word: "Natación", category: "Deporte", easyHint: "En el agua / Pileta" },
  { id: "d4", word: "Vóley", category: "Deporte", easyHint: "Red / Pelota" },
  { id: "d5", word: "Boxeo", category: "Deporte", easyHint: "Guantes / Golpes" },
  { id: "d6", word: "Karate", category: "Deporte", easyHint: "Cinturón de colores / Patadas" },
  { id: "d7", word: "Ciclismo", category: "Deporte", easyHint: "En bicicleta / Carrera" },
  { id: "d8", word: "Patinaje", category: "Deporte", easyHint: "Con ruedas o en el hielo" },
  { id: "d9", word: "Golf", category: "Deporte", easyHint: "Palo / Pelota chica" },
  { id: "d10", word: "Surf", category: "Deporte", easyHint: "Tabla / Olas" },

  // MÚSICA
  { id: "m1", word: "Guitarra", category: "Instrumento", easyHint: "Cuerdas / Se rasguea" },
  { id: "m2", word: "Piano", category: "Instrumento", easyHint: "Teclas blancas y negras" },
  { id: "m3", word: "Tambor", category: "Instrumento", easyHint: "Se golpea / Hace ritmo" },
  { id: "m4", word: "Violín", category: "Instrumento", easyHint: "Cuerdas / Se toca con arco" },
  { id: "m5", word: "Flauta", category: "Instrumento", easyHint: "Se sopla / Tiene agujeritos" },
  { id: "m6", word: "Trompeta", category: "Instrumento", easyHint: "Se sopla / De metal" },
  { id: "m7", word: "Micrófono", category: "Instrumento", easyHint: "Se usa para cantar" },
  { id: "m8", word: "Maracas", category: "Instrumento", easyHint: "Se agitan / Hacen sonido" },

  // NATURALEZA 2
  { id: "n1", word: "Viento", category: "Naturaleza", easyHint: "Mueve las hojas" },
  { id: "n2", word: "Trueno", category: "Naturaleza", easyHint: "Ruido fuerte en la tormenta" },
  { id: "n3", word: "Rayo", category: "Naturaleza", easyHint: "Luz en el cielo / Tormenta" },
  { id: "n4", word: "Arcoíris", category: "Naturaleza", easyHint: "Colores en el cielo / Después de la lluvia" },
  { id: "n5", word: "Volcán", category: "Naturaleza", easyHint: "Lava / Erupción" },
  { id: "n6", word: "Desierto", category: "Naturaleza", easyHint: "Arena / Mucho calor" },
  { id: "n7", word: "Bosque", category: "Naturaleza", easyHint: "Muchos árboles juntos" },
  { id: "n8", word: "Isla", category: "Naturaleza", easyHint: "Tierra rodeada de agua" },
  { id: "n9", word: "Roca", category: "Naturaleza", easyHint: "Dura / De piedra" },
  { id: "n10", word: "Estrella fugaz", category: "Naturaleza", easyHint: "Cruza el cielo de noche" },

  // ESCUELA
  { id: "e1", word: "Lápiz", category: "Útil escolar", easyHint: "Para escribir / Se puede borrar" },
  { id: "e2", word: "Tijera", category: "Útil escolar", easyHint: "Para cortar papel" },
  { id: "e3", word: "Cuaderno", category: "Útil escolar", easyHint: "Hojas para escribir" },
  { id: "e4", word: "Libro", category: "Útil escolar", easyHint: "Tiene páginas para leer" },
  { id: "e5", word: "Pizarrón", category: "Útil escolar", easyHint: "La maestra escribe ahí" },
  { id: "e6", word: "Regla", category: "Útil escolar", easyHint: "Para medir / Líneas rectas" },
  { id: "e7", word: "Calculadora", category: "Útil escolar", easyHint: "Para hacer cuentas" },
  { id: "e8", word: "Bolígrafo", category: "Útil escolar", easyHint: "Para escribir con tinta" },

  // CUERPO
  { id: "b1", word: "Mano", category: "Cuerpo", easyHint: "Tiene dedos / Agarra cosas" },
  { id: "b2", word: "Pie", category: "Cuerpo", easyHint: "Sirve para caminar" },
  { id: "b3", word: "Ojo", category: "Cuerpo", easyHint: "Sirve para ver" },
  { id: "b4", word: "Nariz", category: "Cuerpo", easyHint: "Sirve para oler" },
  { id: "b5", word: "Oreja", category: "Cuerpo", easyHint: "Sirve para oír" },
  { id: "b6", word: "Boca", category: "Cuerpo", easyHint: "Sirve para hablar y comer" },
  { id: "b7", word: "Diente", category: "Cuerpo", easyHint: "Blanco / Sirve para morder" },
  { id: "b8", word: "Pelo", category: "Cuerpo", easyHint: "Está en la cabeza / Se peina" },
  { id: "b9", word: "Corazón", category: "Cuerpo", easyHint: "Late / Bombea la sangre" },
];
