import type { ImpostorWord } from "./types";

export const IMPOSTOR_WORDS_ES: ImpostorWord[] = [
  // ANIMALES
  { id: "a1", word: "Perro", category: "Animal", easyHint: "Fiel / Ladra" },
  { id: "a2", word: "Gato", category: "Animal", easyHint: "Miau / Araña" },
  { id: "a3", word: "Caballo", category: "Animal", easyHint: "Cabalgar / Relincha" },
  { id: "a4", word: "Vaca", category: "Animal", easyHint: "Leche / Muu" },
  { id: "a5", word: "Cerdo", category: "Animal", easyHint: "Rosa / Oink" },
  { id: "a6", word: "Oveja", category: "Animal", easyHint: "Lana / Bee" },
  { id: "a7", word: "Gallina", category: "Animal", easyHint: "Huevos / Clo clo" },
  { id: "a8", word: "Pato", category: "Animal", easyHint: "Agua / Cuac" },
  { id: "a9", word: "León", category: "Animal salvaje", easyHint: "Rey de la selva" },
  { id: "a10", word: "Tigre", category: "Animal salvaje", easyHint: "Rayas / Feroz" },
  { id: "a11", word: "Elefante", category: "Animal salvaje", easyHint: "Trompa / Grande" },
  { id: "a12", word: "Jirafa", category: "Animal salvaje", easyHint: "Cuello largo" },
  { id: "a13", word: "Mono", category: "Animal salvaje", easyHint: "Bananas / Árboles" },
  { id: "a14", word: "Oso", category: "Animal salvaje", easyHint: "Miel / Hiberna" },
  { id: "a15", word: "Serpiente", category: "Animal salvaje", easyHint: "Repta / Veneno" },
  { id: "a16", word: "Pájaro", category: "Animal volador", easyHint: "Alas / Nido" },
  { id: "a17", word: "Pez", category: "Animal acuático", easyHint: "Nada / Escamas" },
  { id: "a18", word: "Tiburón", category: "Animal acuático", easyHint: "Aleta / Peligroso" },
  { id: "a19", word: "Ballena", category: "Animal acuático", easyHint: "Gigante marino" },
  { id: "a20", word: "Delfín", category: "Animal acuático", easyHint: "Inteligente / Salta" },

  // COMIDAS Y FRUTAS
  { id: "c1", word: "Manzana", category: "Fruta", easyHint: "Roja / Blancanieves" },
  { id: "c2", word: "Banana", category: "Fruta", easyHint: "Amarilla / Monos" },
  { id: "c3", word: "Naranja", category: "Fruta", easyHint: "Jugo / Cítrico" },
  { id: "c4", word: "Uva", category: "Fruta", easyHint: "Racimo / Vino" },
  { id: "c5", word: "Fresa", category: "Fruta", easyHint: "Roja / Pequeña" },
  { id: "c6", word: "Sandía", category: "Fruta", easyHint: "Verde por fuera / Roja por dentro" },
  { id: "c7", word: "Melón", category: "Fruta", easyHint: "Redondo / Dulce" },
  { id: "c8", word: "Limón", category: "Fruta", easyHint: "Ácido / Amarillo" },
  { id: "c9", word: "Tomate", category: "Verdura", easyHint: "Rojo / Ensalada" },
  { id: "c10", word: "Zanahoria", category: "Verdura", easyHint: "Naranja / Conejo" },
  { id: "c11", word: "Papa", category: "Verdura", easyHint: "Fritas / Puré" },
  { id: "c12", word: "Cebolla", category: "Verdura", easyHint: "Hace llorar" },
  { id: "c13", word: "Lechuga", category: "Verdura", easyHint: "Hojas verdes" },
  { id: "c14", word: "Hamburguesa", category: "Comida", easyHint: "Pan y carne" },
  { id: "c15", word: "Pizza", category: "Comida", easyHint: "Queso / Porciones" },
  { id: "c16", word: "Helado", category: "Postre", easyHint: "Frío / Cono" },
  { id: "c17", word: "Chocolate", category: "Postre", easyHint: "Cacao / Dulce" },
  { id: "c18", word: "Galleta", category: "Postre", easyHint: "Horno / Chips" },
  { id: "c19", word: "Pastel", category: "Postre", easyHint: "Cumpleaños / Velas" },
  { id: "c20", word: "Caramelo", category: "Dulce", easyHint: "Azúcar / Envoltorio" },

  // OBJETOS DE LA CASA
  { id: "o1", word: "Cama", category: "Mueble", easyHint: "Dormir / Colchón" },
  { id: "o2", word: "Silla", category: "Mueble", easyHint: "Sentarse / 4 patas" },
  { id: "o3", word: "Mesa", category: "Mueble", easyHint: "Comer sobre ella" },
  { id: "o4", word: "Sofá", category: "Mueble", easyHint: "Living / Descanso" },
  { id: "o5", word: "Puerta", category: "Parte de la casa", easyHint: "Abrir / Cerrar" },
  { id: "o6", word: "Ventana", category: "Parte de la casa", easyHint: "Mirar afuera / Vidrio" },
  { id: "o7", word: "Televisión", category: "Electrodoméstico", easyHint: "Pantalla / Control remoto" },
  { id: "o8", word: "Refrigerador", category: "Electrodoméstico", easyHint: "Enfría la comida" },
  { id: "o9", word: "Microondas", category: "Electrodoméstico", easyHint: "Calienta rápido" },
  { id: "o10", word: "Lavadora", category: "Electrodoméstico", easyHint: "Limpia la ropa" },
  { id: "o11", word: "Plato", category: "Utensilio de cocina", easyHint: "Redondo / Servir comida" },
  { id: "o12", word: "Vaso", category: "Utensilio de cocina", easyHint: "Beber agua / Cristal" },
  { id: "o13", word: "Tenedor", category: "Utensilio de cocina", easyHint: "Pinchos / Comer" },
  { id: "o14", word: "Cuchara", category: "Utensilio de cocina", easyHint: "Sopa / Postre" },
  { id: "o15", word: "Cuchillo", category: "Utensilio de cocina", easyHint: "Cortar carne" },
  { id: "o16", word: "Toalla", category: "Cosa del baño", easyHint: "Secarse el cuerpo" },
  { id: "o17", word: "Jabón", category: "Cosa del baño", easyHint: "Espuma / Limpieza" },
  { id: "o18", word: "Cepillo de dientes", category: "Cosa del baño", easyHint: "Boca limpia / Pasta" },
  { id: "o19", word: "Peine", category: "Cosa del baño", easyHint: "Pelo / Desenredar" },
  { id: "o20", word: "Espejo", category: "Cosa del baño/habitación", easyHint: "Reflejo" },

  // PROFESIONES
  { id: "p1", word: "Policía", category: "Profesión", easyHint: "Uniforme azul / Arresta" },
  { id: "p2", word: "Bombero", category: "Profesión", easyHint: "Apaga fuego / Manguera" },
  { id: "p3", word: "Médico", category: "Profesión", easyHint: "Cura enfermos / Hospital" },
  { id: "p4", word: "Enfermera", category: "Profesión", easyHint: "Ayuda al doctor" },
  { id: "p5", word: "Profesor", category: "Profesión", easyHint: "Enseña / Escuela" },
  { id: "p6", word: "Astronauta", category: "Profesión", easyHint: "Viaja al espacio" },
  { id: "p7", word: "Piloto", category: "Profesión", easyHint: "Vuela aviones" },
  { id: "p8", word: "Cantante", category: "Profesión", easyHint: "Micrófono / Música" },
  { id: "p9", word: "Actor", category: "Profesión", easyHint: "Películas / Teatro" },
  { id: "p10", word: "Futbolista", category: "Deporte", easyHint: "Goles / Balón" },
  { id: "p11", word: "Cocinero", category: "Profesión", easyHint: "Prepara comida / Chef" },
  { id: "p12", word: "Cartero", category: "Profesión", easyHint: "Entrega cartas" },
  { id: "p13", word: "Mecánico", category: "Profesión", easyHint: "Arregla autos" },
  { id: "p14", word: "Peluquero", category: "Profesión", easyHint: "Corta el pelo" },
  { id: "p15", word: "Granjero", category: "Profesión", easyHint: "Tractor / Cultivos" },

  // JUGUETES, VEHICULOS Y NATURALEZA
  { id: "j1", word: "Pelota", category: "Juguete/Deporte", easyHint: "Redonda / Rebota" },
  { id: "j2", word: "Muñeca", category: "Juguete", easyHint: "Jugar a casita / Bebé" },
  { id: "j3", word: "Coche de juguete", category: "Juguete", easyHint: "Ruedas pequeñas" },
  { id: "j4", word: "Rompecabezas", category: "Juego", easyHint: "Piezas / Armar" },
  { id: "j5", word: "Bicicleta", category: "Vehículo", easyHint: "Dos ruedas / Pedales" },
  { id: "j6", word: "Coche", category: "Vehículo", easyHint: "Cuatro ruedas / Motor" },
  { id: "j7", word: "Avión", category: "Vehículo", easyHint: "Vuela / Cielo" },
  { id: "j8", word: "Barco", category: "Vehículo", easyHint: "Flota / Mar" },
  { id: "j9", word: "Tren", category: "Vehículo", easyHint: "Vías / Vagones" },
  { id: "j10", word: "Autobús", category: "Vehículo", easyHint: "Transporte público / Pasajeros" },
  { id: "j11", word: "Sol", category: "Naturaleza", easyHint: "Día / Amarillo y caliente" },
  { id: "j12", word: "Luna", category: "Naturaleza", easyHint: "Noche / Blanca" },
  { id: "j13", word: "Estrella", category: "Naturaleza", easyHint: "Brilla de noche" },
  { id: "j14", word: "Nube", category: "Naturaleza", easyHint: "Blanca / En el cielo" },
  { id: "j15", word: "Lluvia", category: "Naturaleza", easyHint: "Gotas de agua" },
  { id: "j16", word: "Nieve", category: "Naturaleza", easyHint: "Fría / Copos blancos" },
  { id: "j17", word: "Árbol", category: "Naturaleza", easyHint: "Tronco / Hojas verdes" },
  { id: "j18", word: "Flor", category: "Naturaleza", easyHint: "Pétalos / Primavera" },
  { id: "j19", word: "Montaña", category: "Naturaleza", easyHint: "Pico alto / Escalar" },
  { id: "j20", word: "Río", category: "Naturaleza", easyHint: "Agua que fluye" },
  { id: "j21", word: "Playa", category: "Naturaleza", easyHint: "Arena y mar" },
  { id: "j22", word: "Rojo", category: "Color", easyHint: "Color de la sangre/fuego" },
  { id: "j23", word: "Azul", category: "Color", easyHint: "Color del cielo/mar" },
  { id: "j24", word: "Verde", category: "Color", easyHint: "Color del pasto" },
  { id: "j25", word: "Amarillo", category: "Color", easyHint: "Color del sol" },
];
